// SPDX-License-Identifier: AGPL-3.0-or-later

package fileformat

import (
	"strings"
	"testing"
)

// byteParsers is every Flipper-file parser that takes raw file bytes.
// These run over untrusted SD-card content (a captured .sub / .ir /
// .nfc / .rfid file, a freqman library), so none may panic on a
// truncated, mis-keyed, or garbage file — the contract is "return an
// error or a partial struct, never panic".
var byteParsers = map[string]func([]byte) (any, error){
	"ParseSub":     func(b []byte) (any, error) { return ParseSub(b) },
	"ParseIR":      func(b []byte) (any, error) { return ParseIR(b) },
	"ParseNFC":     func(b []byte) (any, error) { return ParseNFC(b) },
	"ParseRFID":    func(b []byte) (any, error) { return ParseRFID(b) },
	"ParseFreqman": func(b []byte) (any, error) { return ParseFreqman(b) },
}

// malformedFileInputs is the deterministic battery fed to every
// file-byte parser. These mirror the degenerate shapes an operator
// hits with a truncated capture, a half-written SD file, mixed line
// endings, or a key with no value / value with no key.
var malformedFileInputs = []string{
	"",
	"\n",
	"\r\n",
	"\x00",
	":",
	"Filetype:",
	"Filetype: Flipper SubGhz Key File",
	"Version:",
	"Version: ",
	"Version: notanumber",
	"Frequency:",
	"Frequency: 433920000",
	"Protocol",
	"Protocol: ",
	"Key: ",
	"Key: ZZ ZZ",
	"RAW_Data:",
	"RAW_Data: 1 -1 notanumber 3",
	"Block 0:",
	"Block notanumber: 00 11 22",
	"d=",
	"f=,a=,b=",
	"=value",
	"key=",
	strings.Repeat("A", 8192),
	strings.Repeat("Block 999999999: 00\n", 64),
	strings.Repeat(":\n", 4096),
	strings.Repeat("RAW_Data: "+strings.Repeat("1 ", 256)+"\n", 8),
}

// TestFileParsers_MalformedInputNeverPanics is the fast CI gate: every
// file-byte parser is driven with the degenerate battery and must not
// panic. A new parser added without bounds-checking on a short or
// mis-keyed file would pass its happy-path tests but trip here.
func TestFileParsers_MalformedInputNeverPanics(t *testing.T) {
	for _, in := range malformedFileInputs {
		for name, fn := range byteParsers {
			func() {
				defer func() {
					if r := recover(); r != nil {
						t.Errorf("%s panicked on %q: %v", name, truncate(in), r)
					}
				}()
				_, _ = fn([]byte(in))
			}()
		}
	}
	// ParseNRF24Addresses takes a string, not file bytes — sweep it too.
	for _, in := range malformedFileInputs {
		func() {
			defer func() {
				if r := recover(); r != nil {
					t.Errorf("ParseNRF24Addresses panicked on %q: %v", truncate(in), r)
				}
			}()
			_, _, _ = ParseNRF24Addresses(in)
		}()
	}
}

// FuzzFileFormatParsers drives every Flipper-file parser with
// fuzzer-generated bytes. Flipper files are key:value text with a few
// length- and index-bearing fields (Version, Block <n>, RAW_Data
// token lists, freqman f=/a=/b= tokens), so the fuzzer explores the
// strconv / split / index space the fixed battery only samples. Deep
// local exploration: `go test -fuzz=FuzzFileFormatParsers`.
func FuzzFileFormatParsers(f *testing.F) {
	for _, s := range malformedFileInputs {
		f.Add([]byte(s))
	}
	// A couple of well-formed seeds so the fuzzer has valid structure
	// to mutate from.
	f.Add([]byte("Filetype: Flipper SubGhz Key File\nVersion: 1\nFrequency: 433920000\nPreset: FuriHalSubGhzPresetOok650Async\nProtocol: Princeton\nBit: 24\nKey: 00 00 00 00 00 12 34 56\n"))
	f.Add([]byte("Filetype: Flipper NFC device\nVersion: 4\nDevice type: Mifare Classic\nUID: 04 11 22 33\nBlock 0: 04 11 22 33 44 55 66 77 88 99 AA BB CC DD EE FF\n"))
	f.Add([]byte("Filetype: IR signals file\nVersion: 1\nname: Power\ntype: parsed\nprotocol: NEC\naddress: 04 00 00 00\ncommand: 08 00 00 00\n"))

	f.Fuzz(func(t *testing.T, data []byte) {
		for name, fn := range byteParsers {
			func() {
				defer func() {
					if r := recover(); r != nil {
						t.Errorf("%s panicked on %d-byte input %q: %v",
							name, len(data), truncate(string(data)), r)
					}
				}()
				_, _ = fn(data)
			}()
		}
		func() {
			defer func() {
				if r := recover(); r != nil {
					t.Errorf("ParseNRF24Addresses panicked on %q: %v", truncate(string(data)), r)
				}
			}()
			_, _, _ = ParseNRF24Addresses(string(data))
		}()
	})
}

func truncate(s string) string {
	if len(s) > 80 {
		return s[:80] + "…"
	}
	return s
}
