// Package roca detects RSA public keys vulnerable to CVE-2017-15361 (ROCA):
// the Infineon RSALib flaw that generated factorable primes of the form
// p = k*M + (65537^a mod M), making the modulus practically factorable by the
// Coppersmith-based attack of Nemec et al. (CCS 2017). Affected keys were
// produced by Infineon TPMs, Yubikey 4/Neo, Gemalto IDPrime, Estonian/Slovak
// eID cards, and code-signing/SSH keys generated on that hardware.
//
// The detector implements the public, fast *fingerprint* test from the
// reference tool (crocs-muni/roca, roca/detect.py — has_fingerprint_moduli):
// for each of 38 small primes p_i, the ROCA generator structure forces the
// residue (modulus mod p_i) into a small subgroup, so 1<<(modulus mod p_i)
// must land in a precomputed marker bitmask prints[i]. A vulnerable modulus
// passes all 38 checks; any miss clears it. The primes and markers are
// transcribed verbatim from that file.
//
// The fingerprint is a *screen*, not a factorisation: it has a negligible but
// non-zero false-positive rate (a flagged key is overwhelmingly likely
// ROCA-vulnerable but is confirmed only by the full Coppersmith attack), and
// it never flags a key generated by a sound RSA library. We surface that
// caveat in the Note rather than overclaiming.
//
// Wrap-vs-native: native — pure math/big + crypto/x509 + a native ssh-rsa
// wire parser; no new go.mod dependency. crypto/x509 and encoding/pem are
// stdlib, and ssh-rsa is parsed directly off the base64 wire format so the
// x/crypto/ssh surface (and its govulncheck advisories) is not pulled in.
package roca

import (
	"crypto/rsa"
	"crypto/x509"
	"encoding/base64"
	"encoding/binary"
	"encoding/pem"
	"errors"
	"fmt"
	"math/big"
	"strings"
)

// rocaPrimes is the 38-prime basis of the ROCA fingerprint, transcribed
// verbatim from crocs-muni/roca detect.py (self.primes).
var rocaPrimes = []int64{
	3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71,
	73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151,
	157, 163, 167,
}

// rocaPrintStrings is the 38 marker bitmasks (self.prints in detect.py), kept
// as decimal strings because the larger markers exceed 64 bits. Index i pairs
// with rocaPrimes[i]: a modulus is fingerprinted iff bit (modulus mod
// rocaPrimes[i]) is set in rocaPrints[i] for every i.
var rocaPrintStrings = []string{
	"6", "30", "126", "1026", "5658", "107286", "199410", "8388606",
	"536870910", "2147483646", "67109890", "2199023255550", "8796093022206",
	"140737488355326", "5310023542746834", "576460752303423486",
	"1455791217086302986", "147573952589676412926", "20052041432995567486",
	"6041388139249378920330", "207530445072488465666",
	"9671406556917033397649406", "618970019642690137449562110",
	"79228162521181866724264247298", "2535301200456458802993406410750",
	"1760368345969468176824550810518", "50079290986288516948354744811034",
	"473022961816146413042658758988474",
	"10384593717069655257060992658440190",
	"144390480366845522447407333004847678774",
	"2722258935367507707706996859454145691646",
	"174224571863520493293247799005065324265470",
	"696898287454081973172991196020261297061886",
	"713623846352979940529142984724747568191373310",
	"1800793591454480341970779146165214289059119882",
	"126304807362733370595828809000324029340048915994",
	"11692013098647223345629478661730264157247460343806",
	"187072209578355573530071658587684226515959365500926",
}

// rocaPrints is rocaPrintStrings parsed once into big.Int markers.
var rocaPrints = func() []*big.Int {
	out := make([]*big.Int, len(rocaPrintStrings))
	for i, s := range rocaPrintStrings {
		n, ok := new(big.Int).SetString(s, 10)
		if !ok {
			// Unreachable: the table is a compile-time constant. A panic here
			// means the table was edited incorrectly and must be fixed.
			panic("roca: bad marker constant: " + s)
		}
		out[i] = n
	}
	return out
}()

// HasFingerprint reports whether modulus carries the ROCA fingerprint. It is
// the in-tree port of has_fingerprint_moduli: for every prime p_i, bit
// (modulus mod p_i) must be set in the marker prints[i]; the first miss clears
// the key. A non-positive modulus is never fingerprinted.
func HasFingerprint(modulus *big.Int) bool {
	if modulus == nil || modulus.Sign() <= 0 {
		return false
	}
	rem := new(big.Int)
	p := new(big.Int)
	for i, prime := range rocaPrimes {
		p.SetInt64(prime)
		rem.Mod(modulus, p)
		// rem < prime <= 167, so it fits an int bit index.
		if rocaPrints[i].Bit(int(rem.Int64())) == 0 {
			return false
		}
	}
	return true
}

// Result is the outcome of a Detect call.
type Result struct {
	// Vulnerable is true when the modulus carries the ROCA fingerprint.
	Vulnerable bool `json:"vulnerable"`
	// KeyBits is the bit length of the modulus.
	KeyBits int `json:"key_bits"`
	// Source names how the modulus was obtained: "modulus", "pem-pkix",
	// "pem-pkcs1", "certificate", or "ssh-rsa".
	Source string `json:"source"`
	// ModulusHex is the modulus in hex, for cross-checking against other tools.
	ModulusHex string `json:"modulus_hex"`
	// Note carries the ROCA caveat / interpretation guidance.
	Note string `json:"note"`
}

const vulnerableNote = "ROCA fingerprint present: this key was almost certainly generated by the " +
	"Infineon RSALib (CVE-2017-15361) and its private key is practically factorable. " +
	"Treat it as compromised — revoke and reissue. The fingerprint is a fast screen, not a " +
	"factorisation; full confirmation is the Coppersmith attack."

const cleanNote = "No ROCA fingerprint: the key was not generated by the vulnerable Infineon RSALib. " +
	"(The fingerprint test never clears a vulnerable key, so a negative is reliable.)"

// Detect parses input — a decimal/hex RSA modulus, a PEM public key (PKIX/SPKI
// or PKCS#1), a PEM X.509 certificate, or an OpenSSH ssh-rsa authorized_key
// line — extracts the RSA modulus, and runs the ROCA fingerprint test.
func Detect(input string) (*Result, error) {
	s := strings.TrimSpace(input)
	if s == "" {
		return nil, errors.New("empty input")
	}

	var (
		modulus *big.Int
		source  string
		err     error
	)
	switch {
	case strings.Contains(s, "-----BEGIN"):
		modulus, source, err = modulusFromPEM(s)
	case strings.HasPrefix(s, "ssh-rsa "):
		modulus, err = modulusFromSSHRSA(s)
		source = "ssh-rsa"
	default:
		modulus, err = parseModulus(s)
		source = "modulus"
	}
	if err != nil {
		return nil, err
	}

	res := &Result{
		Vulnerable: HasFingerprint(modulus),
		KeyBits:    modulus.BitLen(),
		Source:     source,
		ModulusHex: modulus.Text(16),
	}
	if res.Vulnerable {
		res.Note = vulnerableNote
	} else {
		res.Note = cleanNote
	}
	return res, nil
}

// parseModulus reads a bare modulus as hex (0x-prefixed or all-hex) or decimal.
func parseModulus(s string) (*big.Int, error) {
	s = strings.TrimSpace(s)
	body := s
	var base int
	switch {
	case strings.HasPrefix(s, "0x"), strings.HasPrefix(s, "0X"):
		body, base = s[2:], 16
	case isAllDecimal(s):
		base = 10
	case isAllHex(s):
		base = 16
	default:
		return nil, fmt.Errorf("input is neither PEM, ssh-rsa, nor a decimal/hex modulus")
	}
	n, ok := new(big.Int).SetString(body, base)
	if !ok || n.Sign() <= 0 {
		return nil, fmt.Errorf("could not parse modulus")
	}
	return n, nil
}

// modulusFromPEM decodes the first PEM block and extracts an RSA modulus from a
// PKIX/SPKI public key, a PKCS#1 RSA public key, or an X.509 certificate.
func modulusFromPEM(s string) (*big.Int, string, error) {
	block, _ := pem.Decode([]byte(s))
	if block == nil {
		return nil, "", errors.New("no PEM block found")
	}
	switch block.Type {
	case "PUBLIC KEY":
		pub, err := x509.ParsePKIXPublicKey(block.Bytes)
		if err != nil {
			return nil, "", fmt.Errorf("parse PKIX public key: %w", err)
		}
		rk, ok := pub.(*rsa.PublicKey)
		if !ok {
			return nil, "", fmt.Errorf("public key is not RSA (%T)", pub)
		}
		return rk.N, "pem-pkix", nil
	case "RSA PUBLIC KEY":
		rk, err := x509.ParsePKCS1PublicKey(block.Bytes)
		if err != nil {
			return nil, "", fmt.Errorf("parse PKCS#1 public key: %w", err)
		}
		return rk.N, "pem-pkcs1", nil
	case "CERTIFICATE":
		cert, err := x509.ParseCertificate(block.Bytes)
		if err != nil {
			return nil, "", fmt.Errorf("parse certificate: %w", err)
		}
		rk, ok := cert.PublicKey.(*rsa.PublicKey)
		if !ok {
			return nil, "", fmt.Errorf("certificate key is not RSA (%T)", cert.PublicKey)
		}
		return rk.N, "certificate", nil
	default:
		return nil, "", fmt.Errorf("unsupported PEM block type %q", block.Type)
	}
}

// modulusFromSSHRSA parses an "ssh-rsa <base64> [comment]" authorized_key line
// natively off the RFC 4253 wire format: a sequence of uint32-length-prefixed
// strings — the algorithm name "ssh-rsa", the public exponent e, then the
// modulus n. Parsing the wire directly avoids the x/crypto/ssh surface.
func modulusFromSSHRSA(s string) (*big.Int, error) {
	fields := strings.Fields(s)
	if len(fields) < 2 {
		return nil, errors.New("malformed ssh-rsa line")
	}
	raw, err := base64.StdEncoding.DecodeString(fields[1])
	if err != nil {
		return nil, fmt.Errorf("ssh-rsa base64: %w", err)
	}
	algo, rest, err := sshString(raw)
	if err != nil {
		return nil, err
	}
	if string(algo) != "ssh-rsa" {
		return nil, fmt.Errorf("not an ssh-rsa key (algorithm %q)", string(algo))
	}
	_, rest, err = sshString(rest) // public exponent e
	if err != nil {
		return nil, err
	}
	nBytes, _, err := sshString(rest) // modulus n
	if err != nil {
		return nil, err
	}
	n := new(big.Int).SetBytes(nBytes)
	if n.Sign() <= 0 {
		return nil, errors.New("ssh-rsa modulus is empty")
	}
	return n, nil
}

// sshString consumes one uint32-length-prefixed field, returning it and the
// remaining bytes.
func sshString(b []byte) (field, rest []byte, err error) {
	if len(b) < 4 {
		return nil, nil, errors.New("ssh-rsa: truncated length prefix")
	}
	n := binary.BigEndian.Uint32(b[:4])
	if uint64(n) > uint64(len(b)-4) {
		return nil, nil, errors.New("ssh-rsa: field length exceeds buffer")
	}
	return b[4 : 4+n], b[4+n:], nil
}

func isAllDecimal(s string) bool {
	if s == "" {
		return false
	}
	for _, c := range s {
		if c < '0' || c > '9' {
			return false
		}
	}
	return true
}

func isAllHex(s string) bool {
	if s == "" {
		return false
	}
	for _, c := range s {
		isDigit := c >= '0' && c <= '9'
		isLower := c >= 'a' && c <= 'f'
		isUpper := c >= 'A' && c <= 'F'
		if !isDigit && !isLower && !isUpper {
			return false
		}
	}
	return true
}
