package main

import (
	"fmt"
	"strings"
)

// RepoResult holds the extraction and matching outcome for one upstream source.
type RepoResult struct {
	// Source is the upstream repository the content was fetched from.
	Source Source
	// Err is non-nil when the fetch or extraction failed. The remaining
	// fields are zero-valued in that case.
	Err error
	// Tokens is every canonical token ExtractTokens pulled from the README.
	Tokens []string
	// Matched is the subset of Tokens that correspond to at least one
	// registered PromptZero tool name.
	Matched []string
	// Gaps is the subset of Tokens that correspond to no registered tool.
	// These are the candidates the operator should review for possible
	// porting to v0.6+.
	Gaps []string
}

// RenderMarkdown formats results as a GitHub-flavoured markdown document
// suitable for an artifact, PR body, or issue comment.
//
// The output contains:
//   - A header with the generation date.
//   - A summary table: one row per source with token / match / gap counts
//     and coverage percentage.
//   - A per-source section listing the gap tokens (candidates).
func RenderMarkdown(results []RepoResult, date string) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# PromptZero upstream coverage diff — %s\n\n", date)
	fmt.Fprintln(&b, "Gaps are tool/verb candidates found in upstream awesome-flipperzero lists")
	fmt.Fprintln(&b, "that do not match any registered PromptZero tool name. Review them to")
	fmt.Fprintln(&b, "identify features worth porting in a future release.")
	fmt.Fprintln(&b)

	// --- Summary table ---
	fmt.Fprintln(&b, "## Summary")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "| Repository | Tokens | Matched | Gaps | Coverage |")
	fmt.Fprintln(&b, "|---|---:|---:|---:|---:|")

	totalTokens, totalMatched, totalGaps := 0, 0, 0
	for _, r := range results {
		if r.Err != nil {
			fmt.Fprintf(&b, "| %s | — | — | — | fetch error: %v |\n", r.Source.Name, r.Err)
			continue
		}
		pct := 0.0
		if len(r.Tokens) > 0 {
			pct = float64(len(r.Matched)) / float64(len(r.Tokens)) * 100
		}
		fmt.Fprintf(&b, "| %s | %d | %d | %d | %.1f%% |\n",
			r.Source.Name, len(r.Tokens), len(r.Matched), len(r.Gaps), pct)
		totalTokens += len(r.Tokens)
		totalMatched += len(r.Matched)
		totalGaps += len(r.Gaps)
	}

	totalPct := 0.0
	if totalTokens > 0 {
		totalPct = float64(totalMatched) / float64(totalTokens) * 100
	}
	fmt.Fprintf(&b, "| **Total** | **%d** | **%d** | **%d** | **%.1f%%** |\n",
		totalTokens, totalMatched, totalGaps, totalPct)
	fmt.Fprintln(&b)

	// --- Per-source gap sections ---
	fmt.Fprintln(&b, "## Gap candidates by repository")
	fmt.Fprintln(&b)

	for _, r := range results {
		fmt.Fprintf(&b, "### %s\n\n", r.Source.Name)
		if r.Err != nil {
			fmt.Fprintf(&b, "_Fetch failed: %v_\n\n", r.Err)
			continue
		}
		if len(r.Gaps) == 0 {
			fmt.Fprintf(&b, "_No gaps — all tokens matched registered tools._\n\n")
			continue
		}
		fmt.Fprintln(&b, "| Candidate token |")
		fmt.Fprintln(&b, "|---|")
		for _, g := range r.Gaps {
			fmt.Fprintf(&b, "| `%s` |\n", g)
		}
		fmt.Fprintln(&b)
	}

	fmt.Fprintln(&b, "---")
	fmt.Fprintln(&b, "_Generated by `cmd/coverage-diff`. To suppress a token permanently,")
	fmt.Fprintln(&b, "add its canonical form to `docs/coverage/out-of-scope.yaml`._")

	return b.String()
}
