// Package semcache implements a small, durable, on-disk semantic cache
// for LLM-generated payloads (roadmap P2-27).
//
// The cache is keyed by SHA-256 of the *exact* inputs that produce the
// generated bytes — task label, provider name (which transitively
// captures the model), the system prompt, and the serialised message
// list. A second call with the same inputs returns the prior output
// without re-billing the LLM. Entries are stored under
// `~/.promptzero/cache/generations/` (one JSON file per entry).
//
// Eviction is LRU on entry count: when the cache exceeds Capacity,
// the oldest LastAccessed entries are deleted. Operators who want a
// clean slate can `rm -rf ~/.promptzero/cache/generations` — there is
// no in-process state besides a sync.Mutex.
//
// Bypass is by construction: callers who don't want a cache pass nil
// for the *Cache, and the integration site short-circuits.
package semcache

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"sync"
	"time"
)

// DefaultCapacity is the LRU bound enforced by [Evict] when callers
// don't override it. 256 entries × ~32 KiB-per-Result ≈ 8 MiB on
// disk in the worst case — safe for the small SD-card-sized files
// the generate package produces.
const DefaultCapacity = 256

// Cache stores generated payloads keyed by a content hash. A nil
// *Cache is a "no cache" sentinel — Get always reports miss, Put
// is a no-op. Construct with [New].
type Cache struct {
	root     string
	capacity int
	mu       sync.Mutex
}

// Entry is one cached generation. The fields are persisted verbatim
// as JSON; Hits / LastAccessed are mutated on Get to drive LRU
// eviction.
type Entry struct {
	Key          string    `json:"key"`
	Task         string    `json:"task"`
	Provider     string    `json:"provider"`
	Content      string    `json:"content"`
	Created      time.Time `json:"created"`
	LastAccessed time.Time `json:"last_accessed"`
	Hits         int       `json:"hits"`
}

// New constructs a Cache rooted at the given directory. The root is
// created lazily on the first [Cache.Put] call so passing a non-
// existent dir is not an error (matches the snapshot package's
// convention). Capacity ≤ 0 falls back to DefaultCapacity.
func New(root string, capacity int) *Cache {
	if capacity <= 0 {
		capacity = DefaultCapacity
	}
	return &Cache{root: root, capacity: capacity}
}

// DefaultRoot returns ~/.promptzero/cache/generations. Mirrors the
// snapshot package's default so operators recognise the layout.
func DefaultRoot() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".promptzero", "cache", "generations"), nil
}

// Key computes the cache key for an arbitrary tuple of strings. Each
// part is null-terminated before hashing so two part-lists that
// differ only in concatenation boundaries hash differently
// (e.g. ("foo","bar") vs ("fo","obar")). The result is a 64-char
// lowercase hex string.
func Key(parts ...string) string {
	h := sha256.New()
	for _, p := range parts {
		_, _ = h.Write([]byte(p))
		_, _ = h.Write([]byte{0})
	}
	return hex.EncodeToString(h.Sum(nil))
}

// Get returns the cached entry for key, or false on miss. On a hit,
// LastAccessed is updated and Hits incremented before the entry is
// re-serialised — this drives the LRU policy. Errors reading or
// re-writing the entry are swallowed and reported as a miss; the
// cache must never block the generation hot path.
//
// Safe to call with a nil *Cache (always returns miss). Concurrency-
// safe via the cache's internal mutex.
func (c *Cache) Get(key string) (Entry, bool) {
	if c == nil {
		return Entry{}, false
	}
	c.mu.Lock()
	defer c.mu.Unlock()

	path := c.pathFor(key)
	raw, err := os.ReadFile(path)
	if err != nil {
		return Entry{}, false
	}
	var e Entry
	if err := json.Unmarshal(raw, &e); err != nil {
		// Corrupt entry — drop it so the next Put rebuilds.
		_ = os.Remove(path)
		return Entry{}, false
	}
	e.LastAccessed = time.Now().UTC()
	e.Hits++
	if rewritten, err := json.Marshal(&e); err == nil {
		// Best-effort rewrite; a failure here just means the next Get
		// won't see the freshened LastAccessed (still correct, just
		// less LRU-aware).
		_ = os.WriteFile(path, rewritten, 0o644)
	}
	return e, true
}

// Put stores entry under key. Creates the cache directory on first
// use. After a successful write, [Cache.evictLocked] runs to honour
// the LRU bound.
//
// A nil *Cache makes Put a no-op (so generators can unconditionally
// call into the cache without a "if c != nil" wrapper). Errors are
// surfaced — unlike Get, Put failures should be visible at the call
// site so operators see when a cache directory is read-only.
func (c *Cache) Put(key string, e Entry) error {
	if c == nil {
		return nil
	}
	if key == "" {
		return fmt.Errorf("semcache: empty key")
	}

	c.mu.Lock()
	defer c.mu.Unlock()

	if err := os.MkdirAll(c.root, 0o755); err != nil {
		return fmt.Errorf("semcache mkdir: %w", err)
	}

	now := time.Now().UTC()
	if e.Key == "" {
		e.Key = key
	}
	if e.Created.IsZero() {
		e.Created = now
	}
	if e.LastAccessed.IsZero() {
		e.LastAccessed = now
	}

	raw, err := json.MarshalIndent(&e, "", "  ")
	if err != nil {
		return fmt.Errorf("semcache marshal: %w", err)
	}
	path := c.pathFor(key)
	if err := os.WriteFile(path, raw, 0o644); err != nil {
		return fmt.Errorf("semcache write: %w", err)
	}
	c.evictLocked()
	return nil
}

// Clear removes the entire cache directory. Useful for `--clear-cache`
// CLI options or test cleanup. A nil *Cache returns nil — clearing a
// disabled cache is a no-op, not an error.
func (c *Cache) Clear() error {
	if c == nil {
		return nil
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	if err := os.RemoveAll(c.root); err != nil {
		return fmt.Errorf("semcache clear: %w", err)
	}
	return nil
}

// Stats returns a snapshot of the cache state. Used by /stats and the
// future report generator. A nil *Cache yields a zero-value Stats.
func (c *Cache) Stats() (Stats, error) {
	if c == nil {
		return Stats{}, nil
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.statsLocked()
}

// Stats is the shape returned by [Cache.Stats].
type Stats struct {
	Root     string `json:"root"`
	Capacity int    `json:"capacity"`
	Entries  int    `json:"entries"`
	Bytes    int64  `json:"bytes"`
}

func (c *Cache) statsLocked() (Stats, error) {
	st := Stats{Root: c.root, Capacity: c.capacity}
	entries, err := os.ReadDir(c.root)
	if err != nil {
		if os.IsNotExist(err) {
			return st, nil
		}
		return st, err
	}
	for _, d := range entries {
		if d.IsDir() || filepath.Ext(d.Name()) != ".json" {
			continue
		}
		info, err := d.Info()
		if err != nil {
			continue
		}
		st.Entries++
		st.Bytes += info.Size()
	}
	return st, nil
}

// pathFor returns the on-disk path for a given cache key. Keys are
// already 64-char hex from [Key], so they're safe filenames as-is —
// no traversal, no special chars, no collision risk on case-folding
// filesystems.
func (c *Cache) pathFor(key string) string {
	return filepath.Join(c.root, key+".json")
}

// evictLocked deletes the oldest entries (by LastAccessed) until the
// directory holds ≤ c.capacity files. Errors are swallowed: a failed
// eviction means the cache grows beyond its bound until the next Put
// retries — better than blocking the caller on a transient FS issue.
//
// MUST be called with c.mu held.
func (c *Cache) evictLocked() {
	entries, err := os.ReadDir(c.root)
	if err != nil {
		return
	}
	type fileEntry struct {
		path     string
		accessed time.Time
	}
	files := make([]fileEntry, 0, len(entries))
	for _, d := range entries {
		if d.IsDir() || filepath.Ext(d.Name()) != ".json" {
			continue
		}
		path := filepath.Join(c.root, d.Name())
		raw, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		var e Entry
		if err := json.Unmarshal(raw, &e); err != nil {
			// Corrupt entries are evicted unconditionally.
			_ = os.Remove(path)
			continue
		}
		files = append(files, fileEntry{path: path, accessed: e.LastAccessed})
	}
	if len(files) <= c.capacity {
		return
	}
	sort.Slice(files, func(i, j int) bool {
		return files[i].accessed.Before(files[j].accessed)
	})
	excess := len(files) - c.capacity
	for i := 0; i < excess; i++ {
		_ = os.Remove(files[i].path)
	}
}
