package petriage

import (
	"encoding/base64"
	"math"
	"strings"
	"testing"
)

// mingwPE is a real gcc/mingw-built 32-bit Windows console PE (the Go
// toolchain's own debug/pe corpus: gcc-386-mingw-no-symbols-exec). Ground
// truth from debug/pe: Machine i386, 8 sections, subsystem 3 (console),
// AddressOfEntryPoint 0x1280, DllCharacteristics 0 (no ASLR/DEP/CFG), imports
// from KERNEL32.dll + msvcrt.dll including VirtualProtect and GetProcAddress.
const mingwPE = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEIAHJlZ2kAAAAAAAAAAOAADwMLAQIYAA4AAAAeAAAAAgAAgBIAAAAQAAAAIAAAAABAAAAQAAAAAgAABAAAAAEAAAAEAAAAAAAAAACQAAAABAAABlMAAAMAAAAAACAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAABgAAB4AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEgAAAGAAAAAAAAAAAAAAAAAAAAAAAAAC4YAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC50ZXh0AAAAZAwAAAAQAAAADgAAAAQAAAAAAAAAAAAAAAAAAGAAUGAuZGF0YQAAABAAAAAAIAAAAAIAAAASAAAAAAAAAAAAAAAAAABAADDALnJkYXRhAAA0AQAAADAAAAACAAAAFAAAAAAAAAAAAAAAAAAAQAAwQC5laF9mcmFtoAMAAABAAAAABAAAABYAAAAAAAAAAAAAAAAAAEAAMEAuYnNzAAAAAGAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAADDALmlkYXRhAAB4AwAAAGAAAAAEAAAAGgAAAAAAAAAAAAAAAAAAQAAwwC5DUlQAAAAAGAAAAABwAAAAAgAAAB4AAAAAAAAAAAAAAAAAAEAAMMAudGxzAAAAACAAAAAAgAAAAAIAAAAgAAAAAAAAAAAAAAAAAABAADDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFOD7DihNDBAAIXAdBzHRCQIAAAAAMdEJAQCAAAAxwQkAAAAAP/Qg+wMxwQkEBFAAOijCwAAg+wE6DMEAADoDgUAAI1EJCyJRCQQoQAgQADHRCQEAFBAAMcEJARQQADHRCQsAAAAAIlEJAyNRCQoiUQkCOj5CgAAoRhQQACFwHRCix0AYUAAowQgQACJRCQEi0MQiQQk6N4KAAChGFBAAIlEJASLQzCJBCToygoAAKEYUEAAiUQkBItDUIkEJOi2CgAA6LkKAACLFQQgQACJEOj8BQAAg+Tw6FQIAADopwoAAIsAiUQkCKEAUEAAiUQkBKEEUEAAiQQk6FMCAACJw+iMCgAAiRwk6NQKAACNdCYAU4PsKItEJDCLAIsAPZEAAMB3PT2NAADAck27AQAAAMdEJAQAAAAAxwQkCAAAAOhVCgAAg/gBD4T0AAAAhcAPhaAAAAAxwIPEKFvCBACNdgA9lAAAwHRLPZYAAMB0Fz2TAADAdd/rsz0FAADAdEI9HQAAwHXPx0QkBAAAAADHBCQEAAAA6P8JAACD+AF0aYXAdLLHBCQEAAAA/9C4/////+ukMdvpdv///420JgAAAADHRCQEAAAAAMcEJAsAAADoxAkAAIP4AXRKhcAPhHP////HBCQLAAAA/9C4/////+li////xwQkCAAAAP/QuP/////pT////8dEJAQBAAAAxwQkBAAAAOh9CQAAg8j/6TP////HRCQEAQAAAMcEJAsAAADoYQkAAIPI/+kX////kMdEJAQBAAAAxwQkCAAAAOhECQAAhdu4/////w+E9f7//4lEJBzo5gIAAItEJBzp4/7//422AAAAAI28JwAAAACD7BzHBCQBAAAA/xX4YEAA6Gv9//+NdCYAjbwnAAAAAIPsHMcEJAIAAAD/FfhgQADoS/3//410JgCNvCcAAAAAoRBhQAD/4In2jbwnAAAAAKEEYUAA/+CQkJCQkJCQkJBVieWD7BihDCBAAIXAdDrHBCQAMEAA6O0IAACD7ASFwLoAAAAAdBXHRCQEDjBAAIkEJOjZCAAAg+wIicKF0nQJxwQkDCBAAP/SxwQkQBNAAOiL////ycOJ9o28JwAAAABVieVdw5CQkJCQkJCQkJCQVYnlg+Twg+wQ6NIFAADHBCQkMEAA6DYIAAC4AAAAAMnDkJCQZpBmkGaQZpBmkGaQg+wci0QkJIXAdBWD+AN0ELgBAAAAg8QcwgwAkI10JgCLVCQoiUQkBItEJCCJVCQIiQQk6BgHAAC4AQAAAIPEHMIMAI22AAAAAI28JwAAAABWU4PsFIM9KFBAAAKLRCQkdArHBShQQAACAAAAg/gCdBKD+AF0QoPEFLgBAAAAW17CDAC+FHBAAIHuFHBAAMH+AoX2fuEx24sEnRRwQACFwHQC/9CDwwE583Xsg8QUuAEAAABbXsIMAItEJCjHRCQEAQAAAIlEJAiLRCQgiQQk6HwGAADroI12AI28JwAAAAAxwMOQkJCQkJCQkJCQkJCQnJxYicI1AAAgAFCdnFidMdCpAAAgAA+EpQAAAFMxwA+ihcAPhJcAAAC4AQAAAA+i9sYBdAeDDRxQQAAB9saAdAeDDRxQQAAC98IAAIAAdAeDDRxQQAAE98IAAAABdAeDDRxQQAAI98IAAAACdAeDDRxQQAAQgeIAAAAEdAeDDRxQQAAg9sEBdAeDDRxQQABAgOUgdS64AAAAgA+iPQAAAIB2HbgBAACAD6KF0ngigeIAAABAdAqBDRxQQAAAAgAAW/PDgQ0cUEAAgAAAAOvGkIENHFBAAAABAADr0pCQkJDb48OQkJCQkJCQkJCQkJCQU4PsKIsdAGFAAI1EJDTHRCQIFwAAAMdEJAQBAAAAg8NAiVwkDMcEJDgwQACJRCQc6BMGAACLRCQciRwkiUQkCItEJDCJRCQE6AMGAADoBgYAAI20JgAAAACNvCcAAAAAg+xciVwkTInDjUQkJMdEJAgcAAAAiUQkBIkcJIl0JFCJ1ol8JFSJz4lsJFjoBwYAAIPsDIXAD4S6AAAAi0QkOIP4BHUriXwkCIl0JASJHCToqwUAAItcJEyLdCRQi3wkVItsJFiDxFzDjbQmAAAAAIP4QHTQi0QkMI1sJCCJbCQMx0QkCEAAAACJRCQEi0QkJIkEJOinBQAAg+wQi0QkOIl8JAiJdCQEiRwkg/hAD5VEJB6D+AQPlUQkH+hABQAAgHwkHwB0joB8JB4AdIeLRCQgiWwkDIlEJAiLRCQwiUQkBItEJCSJBCToUgUAAIPsEOlf////iVwkCMdEJAQcAAAAxwQkUDBAAOiS/v//ZpChIFBAAIXAdAfDjbYAAAAAuDQxQAAtNDFAAIP4B8cFIFBAAAEAAAB+4IPsLIP4C4lcJCCJdCQkiXwkKA+O3wAAAIs1NDFAAIX2D4WFAAAAix04MUAAhdt1e4sNPDFAALtAMUAAhckPhLkAAAC7NDFAAItDCIP4AQ+FRwEAAIPDDIH7NDFAAA+DgwAAAA+2UwiLcwSLC4P6EI2GAABAAIu5AABAAA+EjgAAAIP6IA+E8AAAAIP6CA+EtAAAAIlUJATHBCS4MEAAx0QkGAAAAADovP3//7s0MUAAgfs0MUAAcy6LUwS5BAAAAI2CAABAAIuSAABAAAMTg8MIiVQkHI1UJBzo6f3//4H7NDFAAHLSi1wkIIt0JCSLfCQog8Qsw5C7NDFAAIsThdJ1rotDBIXAD4Q7////66EPt7YAAEAAZoX2D7fWeQaBygAA//8pyrkCAAAAgeoAAEAAAfqJVCQYjVQkGOiH/f//6Q////9mkA+2EITSD7byeQaBzgD///+J8oHqAABAACnKuQEAAAAB+olUJBiNVCQY6FL9///p2v7//4HBAABAACnPuQQAAAADOI1UJBiJfCQY6DH9///puf7//4lEJATHBCSEMEAA6Lz8//+QkJCQkJCQkJCQkJChCCBAAIsAhcB0H4PsDGaQ/9ChCCBAAI1QBItABIkVCCBAAIXAdemDxAzzw410JgBTg+wYix1QHEAAg/v/dCSF23QP/xSdUBxAAIPrAY12AHXxxwQksBhAAOiy+f//g8QYW8Mx2+sCicONQwGLFIVQHEAAhdJ18OvGjbQmAAAAAIsNJFBAAIXJdAbzw410JgDHBSRQQAABAAAA65SQkJCQVlOD7BTHBCQwUEAA6KcCAACLHUhQQACD7ASF23QtZpCLA4kEJOiWAgAAg+wEicbolAIAAIXAdQyF9nQIi0MEiTQk/9CLWwiF23XVxwQkMFBAAOh5AgAAg+wEg8QUW17Dg+wcoSxQQACJdCQYMfaJXCQUhcB1Donwi1wkFIt0JBiDxBzDx0QkBAwAAADHBCQBAAAA6OABAACFwInDdEeLRCQgxwQkMFBAAIkDi0QkJIlDBOgBAgAAoUhQQACJHUhQQACJQwiD7ATHBCQwUEAA6PwBAACJ8IPsBItcJBSLdCQYg8Qcw77/////64qNdCYAU4PsGKEsUEAAi1wkIIXAdQeDxBgxwFvDxwQkMFBAAOikAQAAixVIUEAAg+wEhdJ0HosCOdh1EetLjbQmAAAAAIsIOdl0H4nCi0IIhcB18ccEJDBQQADohQEAAIPsBIPEGDHAW8OLSAiJSgiJBCToHQEAAMcEJDBQQADoYQEAAIPsBOvai0IIo0hQQACJ0Ovbg+wci0QkJIP4AXREchKD+AN0XbgBAAAAg8Qcw410JgChLFBAAIXAdWihLFBAAIP4AXXgxwQkMFBAAMcFLFBAAAAAAADoDwEAAIPsBOvFZpChLFBAAIXAdCfHBSxQQAABAAAAuAEAAACDxBzDjXQmAKEsUEAAhcB0mugC/v//65PHBCQwUEAA6NQAAACD7ATryOjq/f//65GQkJCQkJCQkP8l7GBAAJCQ/yUIYUAAkJD/JfRgQACQkP8l8GBAAJCQ/yX8YEAAkJD/JShhQACQkP8lJGFAAJCQ/yUcYUAAkJD/JSxhQACQkP8lDGFAAJCQ/yUgYUAAkJD/JRRhQACQkP8lGGFAAJCQ/yXYYEAAkJD/JcBgQACQkP8lyGBAAJCQ/yXMYEAAkJD/JeRgQACQkP8l4GBAAJCQ/yW8YEAAkJD/JdxgQACQkP8lxGBAAJCQ/yXUYEAAkJD/JbhgQACQkP8l0GBAAJCQZpBmkGaQZpBVieVd6Zf2//+QkJCQkJCQ/////0AcQAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wBAAABgHEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsaWJnY2otMTYuZGxsAF9Kdl9SZWdpc3RlckNsYXNzZXMAAABoZWxsbywgd29ybGQAAAAA0BNAAE1pbmd3IHJ1bnRpbWUgZmFpbHVyZToKACAgVmlydHVhbFF1ZXJ5IGZhaWxlZCBmb3IgJWQgYnl0ZXMgYXQgYWRkcmVzcyAlcAAAAAAgIFVua25vd24gcHNldWRvIHJlbG9jYXRpb24gcHJvdG9jb2wgdmVyc2lvbiAlZC4KAAAAICBVbmtub3duIHBzZXVkbyByZWxvY2F0aW9uIGJpdCBzaXplICVkLgoAAABHQ0M6ICh0ZG0tMSkgNS4xLjAAAEdDQzogKHRkbS0xKSA1LjEuMAAAR0NDOiAodGRtLTEpIDUuMS4wAABHQ0M6ICh0ZG0tMSkgNS4xLjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAAXpSAAF8CAEbDAQEiAEAACgAAAAcAAAA4M///wwBAAAAQQ4IgwJDDkBiDjRDDkBMDjxDDkAC1A48AAAAIAAAAEgAAADE0P//YwEAAABBDgiDAkMOMAJFCg4IQcMOBEYLEAAAAGwAAAAQ0v//FQAAAABDDiAQAAAAgAAAABzS//8VAAAAAEMOIBAAAACUAAAAKNL//wcAAAAAAAAAEAAAAKgAAAAk0v//BwAAAAAAAAAUAAAAAAAAAAF6UgABfAgBGwwEBIgBAAAcAAAAHAAAAKjS//9DAAAAAEMOIFUKDgRIC2AOBAAAADgAAAA8AAAA2NL//4YAAAAAQQ4IhgJBDgyDA0MOIGQKDgxGww4IQcYOBEMLawoODEbDDghBxg4EQwsAABAAAAB4AAAALNP//wMAAAAAAAAAFAAAAAAAAAABelIAAXwIARsMBASIAQAAHAAAABwAAAAQ0///3AAAAABdDgiDAgKkww4EQg4IgwIUAAAAAAAAAAF6UgABfAgBGwwEBIgBAAAQAAAAHAAAALjT//8DAAAAAAAAABQAAAAAAAAAAXpSAAF8CAEbDAQEiAEAABgAAAAcAAAAnNP//1IAAAAAQQ4IgwJDDjAAAAA8AAAAOAAAAODT//8OAQAAAEMOYESDBVmGBEaHA0aFAkUOVEMOYHQKxcfGww4ESAtpDlBDDmACUg5QQw5gAAAAJAAAAHgAAACw1P//1AEAAABsDjBPgwSGA4cCAuMKx8bDDgRCCwAAABQAAAAAAAAAAXpSAAF8CAEbDAQEiAEAABQAAAAcAAAAUNb//ywAAAAATg4QXA4EACAAAAA0AAAAaNb//0kAAAAAQQ4IgwJDDiBtCg4IQcMOBEELABAAAABYAAAAlNb//xwAAAAAAAAAFAAAAAAAAAABelIAAXwIARsMBASIAQAAOAAAABwAAACI1v//YAAAAABBDgiGAkEODIMDQw4gTA4cSQ4gUA4cQw4gag4cQw4gQw4MQcMOCEHGDgQANAAAAFgAAACs1v//jAAAAABDDiBJhgJGgwNRCsbDDgRBC3MOHFEOIEwOHEUOIEsKw8YOBEELAAA8AAAAkAAAAATX//+QAAAAAEEOCIMCQw4gUAoOCEPDDgRBC0wOHEkOIG4OHEMOIEMKDghDww4EQQtaDhxDDiAAKAAAANAAAABU1///mAAAAABDDiBYCg4ERQtpDhxDDiBfCg4ERQtcDhxDDiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8YAAAAAAAAAAAAAAYYwAAuGAAAHBgAAAAAAAAAAAAAGxjAADsYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0YQAATGEAAGRhAAByYQAAgmEAAJZhAACoYQAAxGEAANxhAAD6YQAACGIAABpiAAAAAAAAKmIAADpiAABKYgAAWGIAAGpiAAB0YgAAfGIAAIZiAACSYgAAmmIAAKRiAACuYgAAtmIAAMBiAADKYgAA0mIAANxiAAAAAAAANGEAAExhAABkYQAAcmEAAIJhAACWYQAAqGEAAMRhAADcYQAA+mEAAAhiAAAaYgAAAAAAACpiAAA6YgAASmIAAFhiAABqYgAAdGIAAHxiAACGYgAAkmIAAJpiAACkYgAArmIAALZiAADAYgAAymIAANJiAADcYgAAAAAAAM8ARGVsZXRlQ3JpdGljYWxTZWN0aW9uAOwARW50ZXJDcml0aWNhbFNlY3Rpb24AABcBRXhpdFByb2Nlc3MA/gFHZXRMYXN0RXJyb3IAABECR2V0TW9kdWxlSGFuZGxlQQAAQQJHZXRQcm9jQWRkcmVzcwAA3gJJbml0aWFsaXplQ3JpdGljYWxTZWN0aW9uAC4DTGVhdmVDcml0aWNhbFNlY3Rpb24AAHQEU2V0VW5oYW5kbGVkRXhjZXB0aW9uRmlsdGVyAJUEVGxzR2V0VmFsdWUAvQRWaXJ0dWFsUHJvdGVjdAAAvwRWaXJ0dWFsUXVlcnkAADcAX19nZXRtYWluYXJncwBNAF9fcF9fZW52aXJvbgAATwBfX3BfX2Ztb2RlAABjAF9fc2V0X2FwcF90eXBlAACTAF9jZXhpdAAACgFfaW9iAAB/AV9vbmV4aXQAqgFfc2V0bW9kZQAARwJhYm9ydABOAmF0ZXhpdAAAUwJjYWxsb2MAAHECZnJlZQAAeQJmd3JpdGUAAKoCbWVtY3B5AAC0AnB1dHMAAMICc2lnbmFsAADsAnZmcHJpbnRmAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAABLRVJORUwzMi5kbGwAAAAAFGAAABRgAAAUYAAAFGAAABRgAAAUYAAAFGAAABRgAAAUYAAAFGAAABRgAAAUYAAAFGAAABRgAAAUYAAAFGAAABRgAABtc3ZjcnQuZGxsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANATQACAE0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYBAAByAQAAUUEAABHBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="

func decode(t *testing.T, b64 string) *Result {
	t.Helper()
	raw := mustB64(t, b64)
	r, err := Decode(raw)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	return r
}

func TestDecode_MingwPE(t *testing.T) {
	r := decode(t, mingwPE)
	if r.Bits != 32 || r.Machine != "x86" {
		t.Errorf("bits=%d machine=%q, want 32 / x86", r.Bits, r.Machine)
	}
	if !strings.HasPrefix(r.Type, "EXE") {
		t.Errorf("type = %q, want EXE", r.Type)
	}
	if r.Subsystem != "Windows console" {
		t.Errorf("subsystem = %q, want Windows console", r.Subsystem)
	}
	if r.EntryPoint != "0x1280" {
		t.Errorf("entry = %q, want 0x1280", r.EntryPoint)
	}
	if len(r.Sections) != 8 {
		t.Errorf("sections = %d, want 8", len(r.Sections))
	}
	if !contains(r.ImportedDLLs, "KERNEL32.dll") || !contains(r.ImportedDLLs, "msvcrt.dll") {
		t.Errorf("imported DLLs = %v", r.ImportedDLLs)
	}
	if !contains(r.ImportedSymbols, "VirtualProtect") || !contains(r.ImportedSymbols, "GetProcAddress") {
		t.Errorf("imported symbols missing expected entries: %v", r.ImportedSymbols)
	}
	if !contains(r.SuspiciousSymbols, "VirtualProtect") || !contains(r.SuspiciousSymbols, "GetProcAddress") {
		t.Errorf("suspicious symbols = %v, want VirtualProtect + GetProcAddress", r.SuspiciousSymbols)
	}
	// DllCharacteristics is 0 → every mitigation is absent.
	for _, m := range []string{"ASLR", "DEP", "CFG"} {
		if !contains(r.MissingMitigations, m) {
			t.Errorf("missing mitigation %q not reported: %v", m, r.MissingMitigations)
		}
	}
	if len(r.Mitigations) != 0 {
		t.Errorf("mitigations = %v, want none", r.Mitigations)
	}
	if !r.Suspicious || !strings.Contains(r.Note, "SUSPICIOUS") {
		t.Errorf("expected suspicious verdict: %+v", r.SuspiciousReasons)
	}
}

func TestDecode_Errors(t *testing.T) {
	for name, in := range map[string][]byte{
		"empty":   {},
		"not pe":  []byte("ELF this is not a PE"),
		"mz only": []byte("MZ\x00\x00 truncated, no PE header"),
	} {
		if _, err := Decode(in); err == nil {
			t.Errorf("%s: expected error", name)
		}
	}
}

func TestPackerName(t *testing.T) {
	cases := map[string]string{
		"UPX0":             "UPX",
		"UPX1\x00\x00\x00": "UPX",
		".vmp0":            "VMProtect",
		"MPRESS1":          "MPRESS",
		".text":            "",
		".data":            "",
	}
	for in, want := range cases {
		if got := packerName(in); got != want {
			t.Errorf("packerName(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestSuspiciousAPI_CaseAndVariants(t *testing.T) {
	// Lookup lower-cases the symbol, so case and A/W variants all match.
	for _, sym := range []string{"VirtualAllocEx", "writeprocessmemory", "CreateRemoteThread", "URLDownloadToFileW", "ShellExecuteA"} {
		if !suspiciousAPIs[strings.ToLower(sym)] {
			t.Errorf("expected %q to be a suspicious API", sym)
		}
	}
	for _, sym := range []string{"printf", "GetTickCount64", "memcpy"} {
		if suspiciousAPIs[strings.ToLower(sym)] {
			t.Errorf("did not expect %q to be flagged", sym)
		}
	}
}

func TestEntropyExtremes(t *testing.T) {
	// All-zero data → entropy 0; uniformly distributed bytes → ~8.
	zero := make([]byte, 4096)
	if h := shannon(zero); h != 0 {
		t.Errorf("zero entropy = %f, want 0", h)
	}
	uni := make([]byte, 256*16)
	for i := range uni {
		uni[i] = byte(i % 256)
	}
	if h := shannon(uni); h < 7.99 {
		t.Errorf("uniform entropy = %f, want ~8", h)
	}
}

func FuzzDecode(f *testing.F) {
	f.Add(mustB64(f, mingwPE))
	f.Add([]byte("MZ\x00\x00"))
	f.Add([]byte{})
	f.Fuzz(func(_ *testing.T, data []byte) {
		// Must never panic, regardless of input.
		_, _ = Decode(data)
	})
}

// --- test helpers ---------------------------------------------------------

// shannon computes Shannon entropy over a byte slice (independent re-derivation
// of the production math).
func shannon(data []byte) float64 {
	if len(data) == 0 {
		return 0
	}
	var counts [256]int
	for _, b := range data {
		counts[b]++
	}
	n := float64(len(data))
	var h float64
	for _, c := range counts {
		if c == 0 {
			continue
		}
		p := float64(c) / n
		h -= p * math.Log2(p)
	}
	return h
}

func contains(xs []string, s string) bool {
	for _, x := range xs {
		if x == s {
			return true
		}
	}
	return false
}

func mustB64(tb testing.TB, s string) []byte {
	tb.Helper()
	raw, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		tb.Fatalf("base64: %v", err)
	}
	return raw
}
