package kdbx

import (
	"encoding/binary"
	"encoding/hex"
	"testing"
)

// realKDBX4Header is the verbatim outer header of a KDBX4 database generated by
// the pykeepass reference library (password "hunter2"): AES-256 cipher, gzip,
// Argon2d KDF with I=14, M=67108864 (64 MiB), P=2. The expected values were
// cross-checked by decoding the VariantDictionary independently in Python.
const realKDBX4Header = "03d9a29a67fb4bb500000400021000000031c1f2e6bf714350be5805216afc5aff030400" +
	"0000010000000420000000b52178a734d0b577423679d02ab37dd17cb6781861d216c7d3" +
	"2d52c354ab2123071000000090ba3750281556cb96fea4c43545a9760b8b000000000142" +
	"05000000245555494410000000ef636ddf8c29444b91f7a9a403e30a0c05010000004908" +
	"0000000e0000000000000005010000004d08000000000000040000000004010000005004" +
	"00000002000000420100000053200000007839e86543e0449b3d6cc46b95b4bbab7d519c" +
	"7eb01d9cf59d64d82f6ab1a15f04010000005604000000130000000000040000000d0a0d" +
	"0a"

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex: %v", err)
	}
	return b
}

func TestDecode_RealKDBX4(t *testing.T) {
	r, err := Decode(mustHex(t, realKDBX4Header))
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	if r.VersionMajor != 4 || r.VersionMinor != 0 {
		t.Errorf("version = %d.%d, want 4.0", r.VersionMajor, r.VersionMinor)
	}
	if r.Cipher != "AES-256" {
		t.Errorf("cipher = %q, want AES-256", r.Cipher)
	}
	if r.Compression != "gzip" {
		t.Errorf("compression = %q, want gzip", r.Compression)
	}
	if r.KDF != "Argon2d" {
		t.Errorf("kdf = %q, want Argon2d", r.KDF)
	}
	if r.Argon2Iterations != 14 || r.Argon2MemoryBytes != 67108864 || r.Argon2Parallelism != 2 {
		t.Errorf("argon2 I/M/P = %d/%d/%d, want 14/67108864/2",
			r.Argon2Iterations, r.Argon2MemoryBytes, r.Argon2Parallelism)
	}
	if r.HashcatMode != 13400 {
		t.Errorf("hashcat mode = %d, want 13400", r.HashcatMode)
	}
}

// buildKDBX3Header constructs a spec-faithful KDBX 3.1 header: magic + version
// 3.1 + AES cipher + gzip + a TransformRounds field + a 16-byte IV, terminated
// by EndOfHeader. KDBX3 uses uint16 field-size prefixes and has no KDF UUID
// (the KDF is implicitly AES-KDF), so this format is unambiguous.
func buildKDBX3Header(rounds uint64) []byte {
	var b []byte
	put32 := func(v uint32) []byte { x := make([]byte, 4); binary.LittleEndian.PutUint32(x, v); return x }
	put16 := func(v uint16) []byte { x := make([]byte, 2); binary.LittleEndian.PutUint16(x, v); return x }
	b = append(b, put32(sig1)...)
	b = append(b, put32(sig2)...)
	b = append(b, put16(1)...) // minor
	b = append(b, put16(3)...) // major = 3
	field := func(id byte, data []byte) {
		b = append(b, id)
		b = append(b, put16(uint16(len(data)))...)
		b = append(b, data...)
	}
	field(fCipherID, mustHexNoT("31c1f2e6bf714350be5805216afc5aff"))
	field(fCompression, put32(1))
	roundsB := make([]byte, 8)
	binary.LittleEndian.PutUint64(roundsB, rounds)
	field(fTransformRounds, roundsB)
	field(7, make([]byte, 16)) // EncryptionIV
	field(fEndOfHeader, []byte{0x0d, 0x0a, 0x0d, 0x0a})
	return b
}

func mustHexNoT(s string) []byte { b, _ := hex.DecodeString(s); return b }

func TestDecode_KDBX3(t *testing.T) {
	r, err := Decode(buildKDBX3Header(60000))
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	if r.VersionMajor != 3 || r.VersionMinor != 1 {
		t.Errorf("version = %d.%d, want 3.1", r.VersionMajor, r.VersionMinor)
	}
	if r.Cipher != "AES-256" || r.Compression != "gzip" {
		t.Errorf("cipher/compression = %q/%q", r.Cipher, r.Compression)
	}
	if r.KDF != "AES-KDF" {
		t.Errorf("kdf = %q, want AES-KDF (implicit for KDBX3)", r.KDF)
	}
	if r.TransformRounds != 60000 {
		t.Errorf("transform rounds = %d, want 60000", r.TransformRounds)
	}
}

func TestDecode_UnknownCipherSurfacedRaw(t *testing.T) {
	// A KDBX3 header with a made-up cipher UUID must be surfaced as raw hex, not guessed.
	h := buildKDBX3Header(1000)
	// Replace the cipher UUID bytes (right after the first fCipherID marker).
	hx := hex.EncodeToString(h)
	hx = replaceFirst(hx, "31c1f2e6bf714350be5805216afc5aff", "00112233445566778899aabbccddeeff")
	r, err := Decode(mustHex(t, hx))
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	if r.Cipher != "unknown (00112233445566778899aabbccddeeff)" {
		t.Errorf("cipher = %q, want unknown-with-raw-hex", r.Cipher)
	}
}

func replaceFirst(s, old, new string) string {
	i := indexOf(s, old)
	if i < 0 {
		return s
	}
	return s[:i] + new + s[i+len(old):]
}

func indexOf(s, sub string) int {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return i
		}
	}
	return -1
}

func TestDecode_Errors(t *testing.T) {
	cases := map[string][]byte{
		"empty":     {},
		"short":     {0x03, 0xd9},
		"bad magic": append([]byte{0xde, 0xad, 0xbe, 0xef}, make([]byte, 16)...),
		"truncated": mustHex(t, "03d9a29a67fb4bb50000040002"), // header cut mid-field
	}
	for name, raw := range cases {
		if _, err := Decode(raw); err == nil {
			t.Errorf("%s: expected error, got nil", name)
		}
	}
}

func FuzzDecode(f *testing.F) {
	f.Add(mustHexNoT(realKDBX4Header))
	f.Add(buildKDBX3Header(6000))
	f.Add([]byte{0x03, 0xd9, 0xa2, 0x9a})
	f.Fuzz(func(_ *testing.T, raw []byte) {
		_, _ = Decode(raw)
	})
}
