// SPDX-License-Identifier: AGPL-3.0-or-later

package sshkey

import "testing"

// Keys generated by ssh-keygen; the fingerprints / types / comments are exactly
// what `ssh-keygen -l` reports for each.
const (
	edB64 = "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACD/POBULGQ2aQUpE4Dn36rTdHoYRFrk/mN1sP7jMTEl9AAAAJC+igQ7vooEOwAAAAtzc2gtZWQyNTUxOQAAACD/POBULGQ2aQUpE4Dn36rTdHoYRFrk/mN1sP7jMTEl9AAAAEDHWnkLDsZzAJQIpqWjAquInhnDfkYOVuvcwpa/KhXetv884FQsZDZpBSkTgOffqtN0ehhEWuT+Y3Ww/uMxMSX0AAAADGFsaWNlQHZpY3RpbQE="
	edFP  = "SHA256:MZKQua1F1vZJsJHw0RgG/BgnUpAbZZOkJdElEc0lDR4"

	edEncB64 = "b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCJoeUJfJAyefXVIjnVkImsAAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIE3QfnTj+JSSe/XVwnEKB4/gvgGpC/afAbazeqSrpd+zAAAAkIByNQLe05aBFAonf58HZazNz50yfukiakHTNozZsJ1VWz4PaCxZR0YRxMpOWh/03KMsWlV8+rOkx/As21LVLxZXFrzNDpvwSJE4Nqw2429y98MBMOVTU+nzuI8ycvooPNXHBysCn3BgGRkFYP4uOFHCVDvtyx8AlfsPDaikmVrxoQM/9Vfsa+3A+JbF+p1Y/Q=="
	edEncFP  = "SHA256:reHjqbMmpXE9UTPUpQFzJCNWa7eCAIvLfJqy6OBH4cI"

	rsaB64 = "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcnNhAAAAAwEAAQAAAQEAqre6tZJkKgnNQJ6+aqQC8blVuR5+VXDr5z1+dLevWtzea7O1tXxhOb7F75SINTW7NTLqbexS5IU7Tk+ie9PUcwdRIPpUPVgWyodUjClXtfhhjmxj2iEnZclVn/AeEF3QuQmx9zGEyO/JrFe/a11DiiQH9bFlfPndaYUJxyPMkwFK7jB8vYhLR1VSX8G/c9j6TDew5i61aas3V4ZGl7ueS/zs7DyL78n7maqX9v8EDA0N9p9pFPCziEejgjNfdEbhCg2K9lqZUMsdAJGRIMgqxtluSKH8BHfY7GdyHsJF0tmJiPvBWcpUAUdmk8DrHY3HOJHe3Ig/mIbU1+k1UdcmFwAAA8DmYEAJ5mBACQAAAAdzc2gtcnNhAAABAQCqt7q1kmQqCc1Anr5qpALxuVW5Hn5VcOvnPX50t69a3N5rs7W1fGE5vsXvlIg1Nbs1Mupt7FLkhTtOT6J709RzB1Eg+lQ9WBbKh1SMKVe1+GGObGPaISdlyVWf8B4QXdC5CbH3MYTI78msV79rXUOKJAf1sWV8+d1phQnHI8yTAUruMHy9iEtHVVJfwb9z2PpMN7DmLrVpqzdXhkaXu55L/OzsPIvvyfuZqpf2/wQMDQ32n2kU8LOIR6OCM190RuEKDYr2WplQyx0AkZEgyCrG2W5IofwEd9jsZ3IewkXS2YmI+8FZylQBR2aTwOsdjcc4kd7ciD+YhtTX6TVR1yYXAAAAAwEAAQAAAQBBlG2xZWh766MAwVpljdahs+/1unyOZuAARxOmU4+VqIX6uqDBdGPG8n2H4LeINTlSoNoEWwWmynVzSk0hI0kX3QYx1Gf63rV2nJECfLk4ao9TTlj3SMghJjvxwiRSZi+RfWNzkX6wT8jZnyWl4UBaNyglnj1dyoBfEh+k86AZEgPPOltPVTLe3MVSa/oBn3Gt6jmQC2V+EG2SsZoBwaLd1VF4jOnKmrREQt8MaIotPD8pxN9ZcaSypCBEziCEqmkcXers2hCzcINhAJkMhaMV/w6eMc0cContAdR/AkBICIjogAnIo/c8rNPnTdCjF15JSOmD2pj4+wXl0qMtU3B5AAAAgQCCR77LwGq7uIkTH2HDuvsjFPZYDfYJ1apkLfIL2hvs33LVPWXLVHbyRWIODGfWIjebQeoFP2iaGnTQEdEBpZwR1ZePMNY5pL5wLnF/9CNsseZyWGc+VjxC9uFGHTnVpGWGrKSG7p1Xv5jp1bQBRCaswrsELvrdKoPwUbE7Ohoq4wAAAIEA2anQn5zSRYXnZciVt5Z/AFiwkAb/bEpihUM/daTNh4rgEO+vUHVEJvbHVHZe3qz3qh9ektYJneA+Y+O4kkXNFjQeC+IKyutVVp/OqK8kxOsXoVbtetqpGKB/bkN4kR+5ZhP0K968Yf+Gz3wKwdKj5QtixIlK/Z6XqGGdpyeafE8AAACBAMjJMK5XDVFnhaqAskHXCtdUHYxChGq62W8vCJenwx10ra7IhSJ3/adgSXhqxbaLw+ZVo33aD4IsR+DAbHCracYhP8UC4gFGYz6UvloXm8kbnAH7Kai/Cm0PksQ1MPPWvjSFDQLVCLWyAmVGdaWpLTdbgU7WmKj7zN2ykwfRTl+5AAAACHN2Y0Bob3N0AQI="
	rsaFP  = "SHA256:ZQknCC+6oSY+g/uMq6ymqdjcR1g2+TmOrZzCaCSNtD0"
)

func TestUnencryptedEd25519(t *testing.T) {
	r, err := Decode(edB64)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	if r.Encrypted || r.Cipher != "none" {
		t.Errorf("should be unencrypted: cipher=%q enc=%v", r.Cipher, r.Encrypted)
	}
	if len(r.Keys) != 1 || r.Keys[0].Type != "ssh-ed25519" {
		t.Fatalf("keys: %+v", r.Keys)
	}
	if r.Keys[0].Fingerprint != edFP {
		t.Errorf("fingerprint = %q, want %q", r.Keys[0].Fingerprint, edFP)
	}
	if r.Comment != "alice@victim" {
		t.Errorf("comment = %q, want alice@victim", r.Comment)
	}
}

func TestEncryptedEd25519(t *testing.T) {
	r, err := Decode(edEncB64)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	if !r.Encrypted || r.Cipher != "aes256-ctr" {
		t.Errorf("should be encrypted aes256-ctr: cipher=%q enc=%v", r.Cipher, r.Encrypted)
	}
	if r.KDF != "bcrypt" || r.KDFRounds != 24 || r.KDFSaltLen != 16 {
		t.Errorf("kdf = %q rounds=%d saltlen=%d, want bcrypt/24/16", r.KDF, r.KDFRounds, r.KDFSaltLen)
	}
	if r.Keys[0].Fingerprint != edEncFP {
		t.Errorf("fingerprint = %q, want %q", r.Keys[0].Fingerprint, edEncFP)
	}
	// The comment is in the encrypted section — must NOT be guessed.
	if r.Comment != "" {
		t.Errorf("encrypted key comment should be empty, got %q", r.Comment)
	}
	if r.Note == "" {
		t.Error("encrypted key should carry a crack-guidance note")
	}
}

func TestUnencryptedRSA(t *testing.T) {
	r, err := Decode(rsaB64)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	if r.Keys[0].Type != "ssh-rsa" || r.Keys[0].Fingerprint != rsaFP {
		t.Errorf("rsa key: type=%q fp=%q", r.Keys[0].Type, r.Keys[0].Fingerprint)
	}
	if r.Comment != "svc@host" {
		t.Errorf("comment = %q, want svc@host", r.Comment)
	}
}

// TestPEMArmorTolerated confirms the full PEM (with header/footer) decodes too.
func TestPEMArmorTolerated(t *testing.T) {
	pem := "-----BEGIN OPENSSH PRIVATE KEY-----\n" + edB64 + "\n-----END OPENSSH PRIVATE KEY-----\n"
	r, err := Decode(pem)
	if err != nil {
		t.Fatalf("Decode(PEM): %v", err)
	}
	if r.Keys[0].Fingerprint != edFP {
		t.Errorf("PEM decode fingerprint = %q", r.Keys[0].Fingerprint)
	}
}

func TestRejectsMalformed(t *testing.T) {
	for _, c := range []string{
		"",
		"not base64 @@@",
		"aGVsbG8gd29ybGQ=", // valid base64 but wrong magic
	} {
		if _, err := Decode(c); err == nil {
			t.Errorf("Decode(%q): want error, got nil", c)
		}
	}
}
