// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated from Google libphonenumber (the `phonenumbers` library)
// E.164 calling-code → region map and pycountry's ISO-3166 names.
// DO NOT EDIT BY HAND. The E.164 calling codes are a prefix-free set, so an
// ICCID country code (digits after the '89' MII) is parsed unambiguously by
// trying 1-, 2- then 3-digit prefixes against this table.
package iccid

// callingEntry is the country a SIM-issuer E.164 country code belongs to.
// shared is set when the calling code spans multiple territories (e.g. the
// NANP +1, or the +44 British-Isles group), so primaryCountry is indicative.
type callingEntry struct {
	country string
	region  string
	shared  bool
}

var callingCodeTable = map[string]callingEntry{
	"1":   {"United States", "US", true},
	"7":   {"Russian Federation", "RU", true},
	"20":  {"Egypt", "EG", false},
	"27":  {"South Africa", "ZA", false},
	"30":  {"Greece", "GR", false},
	"31":  {"Netherlands", "NL", false},
	"32":  {"Belgium", "BE", false},
	"33":  {"France", "FR", false},
	"34":  {"Spain", "ES", false},
	"36":  {"Hungary", "HU", false},
	"39":  {"Italy", "IT", true},
	"40":  {"Romania", "RO", false},
	"41":  {"Switzerland", "CH", false},
	"43":  {"Austria", "AT", false},
	"44":  {"United Kingdom", "GB", true},
	"45":  {"Denmark", "DK", false},
	"46":  {"Sweden", "SE", false},
	"47":  {"Norway", "NO", true},
	"48":  {"Poland", "PL", false},
	"49":  {"Germany", "DE", false},
	"51":  {"Peru", "PE", false},
	"52":  {"Mexico", "MX", false},
	"53":  {"Cuba", "CU", false},
	"54":  {"Argentina", "AR", false},
	"55":  {"Brazil", "BR", false},
	"56":  {"Chile", "CL", false},
	"57":  {"Colombia", "CO", false},
	"58":  {"Venezuela, Bolivarian Republic of", "VE", false},
	"60":  {"Malaysia", "MY", false},
	"61":  {"Australia", "AU", true},
	"62":  {"Indonesia", "ID", false},
	"63":  {"Philippines", "PH", false},
	"64":  {"New Zealand", "NZ", false},
	"65":  {"Singapore", "SG", false},
	"66":  {"Thailand", "TH", false},
	"81":  {"Japan", "JP", false},
	"82":  {"Korea, Republic of", "KR", false},
	"84":  {"Viet Nam", "VN", false},
	"86":  {"China", "CN", false},
	"90":  {"Türkiye", "TR", false},
	"91":  {"India", "IN", false},
	"92":  {"Pakistan", "PK", false},
	"93":  {"Afghanistan", "AF", false},
	"94":  {"Sri Lanka", "LK", false},
	"95":  {"Myanmar", "MM", false},
	"98":  {"Iran, Islamic Republic of", "IR", false},
	"211": {"South Sudan", "SS", false},
	"212": {"Morocco", "MA", true},
	"213": {"Algeria", "DZ", false},
	"216": {"Tunisia", "TN", false},
	"218": {"Libya", "LY", false},
	"220": {"Gambia", "GM", false},
	"221": {"Senegal", "SN", false},
	"222": {"Mauritania", "MR", false},
	"223": {"Mali", "ML", false},
	"224": {"Guinea", "GN", false},
	"225": {"Côte d'Ivoire", "CI", false},
	"226": {"Burkina Faso", "BF", false},
	"227": {"Niger", "NE", false},
	"228": {"Togo", "TG", false},
	"229": {"Benin", "BJ", false},
	"230": {"Mauritius", "MU", false},
	"231": {"Liberia", "LR", false},
	"232": {"Sierra Leone", "SL", false},
	"233": {"Ghana", "GH", false},
	"234": {"Nigeria", "NG", false},
	"235": {"Chad", "TD", false},
	"236": {"Central African Republic", "CF", false},
	"237": {"Cameroon", "CM", false},
	"238": {"Cabo Verde", "CV", false},
	"239": {"Sao Tome and Principe", "ST", false},
	"240": {"Equatorial Guinea", "GQ", false},
	"241": {"Gabon", "GA", false},
	"242": {"Congo", "CG", false},
	"243": {"Congo, The Democratic Republic of the", "CD", false},
	"244": {"Angola", "AO", false},
	"245": {"Guinea-Bissau", "GW", false},
	"246": {"British Indian Ocean Territory", "IO", false},
	"247": {"AC", "AC", false},
	"248": {"Seychelles", "SC", false},
	"249": {"Sudan", "SD", false},
	"250": {"Rwanda", "RW", false},
	"251": {"Ethiopia", "ET", false},
	"252": {"Somalia", "SO", false},
	"253": {"Djibouti", "DJ", false},
	"254": {"Kenya", "KE", false},
	"255": {"Tanzania, United Republic of", "TZ", false},
	"256": {"Uganda", "UG", false},
	"257": {"Burundi", "BI", false},
	"258": {"Mozambique", "MZ", false},
	"260": {"Zambia", "ZM", false},
	"261": {"Madagascar", "MG", false},
	"262": {"Réunion", "RE", true},
	"263": {"Zimbabwe", "ZW", false},
	"264": {"Namibia", "NA", false},
	"265": {"Malawi", "MW", false},
	"266": {"Lesotho", "LS", false},
	"267": {"Botswana", "BW", false},
	"268": {"Eswatini", "SZ", false},
	"269": {"Comoros", "KM", false},
	"290": {"Saint Helena, Ascension and Tristan da Cunha", "SH", true},
	"291": {"Eritrea", "ER", false},
	"297": {"Aruba", "AW", false},
	"298": {"Faroe Islands", "FO", false},
	"299": {"Greenland", "GL", false},
	"350": {"Gibraltar", "GI", false},
	"351": {"Portugal", "PT", false},
	"352": {"Luxembourg", "LU", false},
	"353": {"Ireland", "IE", false},
	"354": {"Iceland", "IS", false},
	"355": {"Albania", "AL", false},
	"356": {"Malta", "MT", false},
	"357": {"Cyprus", "CY", false},
	"358": {"Finland", "FI", true},
	"359": {"Bulgaria", "BG", false},
	"370": {"Lithuania", "LT", false},
	"371": {"Latvia", "LV", false},
	"372": {"Estonia", "EE", false},
	"373": {"Moldova, Republic of", "MD", false},
	"374": {"Armenia", "AM", false},
	"375": {"Belarus", "BY", false},
	"376": {"Andorra", "AD", false},
	"377": {"Monaco", "MC", false},
	"378": {"San Marino", "SM", false},
	"380": {"Ukraine", "UA", false},
	"381": {"Serbia", "RS", false},
	"382": {"Montenegro", "ME", false},
	"383": {"XK", "XK", false},
	"385": {"Croatia", "HR", false},
	"386": {"Slovenia", "SI", false},
	"387": {"Bosnia and Herzegovina", "BA", false},
	"389": {"North Macedonia", "MK", false},
	"420": {"Czechia", "CZ", false},
	"421": {"Slovakia", "SK", false},
	"423": {"Liechtenstein", "LI", false},
	"500": {"Falkland Islands (Malvinas)", "FK", false},
	"501": {"Belize", "BZ", false},
	"502": {"Guatemala", "GT", false},
	"503": {"El Salvador", "SV", false},
	"504": {"Honduras", "HN", false},
	"505": {"Nicaragua", "NI", false},
	"506": {"Costa Rica", "CR", false},
	"507": {"Panama", "PA", false},
	"508": {"Saint Pierre and Miquelon", "PM", false},
	"509": {"Haiti", "HT", false},
	"590": {"Guadeloupe", "GP", true},
	"591": {"Bolivia, Plurinational State of", "BO", false},
	"592": {"Guyana", "GY", false},
	"593": {"Ecuador", "EC", false},
	"594": {"French Guiana", "GF", false},
	"595": {"Paraguay", "PY", false},
	"596": {"Martinique", "MQ", false},
	"597": {"Suriname", "SR", false},
	"598": {"Uruguay", "UY", false},
	"599": {"Curaçao", "CW", true},
	"670": {"Timor-Leste", "TL", false},
	"672": {"Norfolk Island", "NF", false},
	"673": {"Brunei Darussalam", "BN", false},
	"674": {"Nauru", "NR", false},
	"675": {"Papua New Guinea", "PG", false},
	"676": {"Tonga", "TO", false},
	"677": {"Solomon Islands", "SB", false},
	"678": {"Vanuatu", "VU", false},
	"679": {"Fiji", "FJ", false},
	"680": {"Palau", "PW", false},
	"681": {"Wallis and Futuna", "WF", false},
	"682": {"Cook Islands", "CK", false},
	"683": {"Niue", "NU", false},
	"685": {"Samoa", "WS", false},
	"686": {"Kiribati", "KI", false},
	"687": {"New Caledonia", "NC", false},
	"688": {"Tuvalu", "TV", false},
	"689": {"French Polynesia", "PF", false},
	"690": {"Tokelau", "TK", false},
	"691": {"Micronesia, Federated States of", "FM", false},
	"692": {"Marshall Islands", "MH", false},
	"800": {"International / non-geographic", "001", false},
	"808": {"International / non-geographic", "001", false},
	"850": {"Korea, Democratic People's Republic of", "KP", false},
	"852": {"Hong Kong", "HK", false},
	"853": {"Macao", "MO", false},
	"855": {"Cambodia", "KH", false},
	"856": {"Lao People's Democratic Republic", "LA", false},
	"870": {"International / non-geographic", "001", false},
	"878": {"International / non-geographic", "001", false},
	"880": {"Bangladesh", "BD", false},
	"881": {"International / non-geographic", "001", false},
	"882": {"International / non-geographic", "001", false},
	"883": {"International / non-geographic", "001", false},
	"886": {"Taiwan, Province of China", "TW", false},
	"888": {"International / non-geographic", "001", false},
	"960": {"Maldives", "MV", false},
	"961": {"Lebanon", "LB", false},
	"962": {"Jordan", "JO", false},
	"963": {"Syrian Arab Republic", "SY", false},
	"964": {"Iraq", "IQ", false},
	"965": {"Kuwait", "KW", false},
	"966": {"Saudi Arabia", "SA", false},
	"967": {"Yemen", "YE", false},
	"968": {"Oman", "OM", false},
	"970": {"Palestine, State of", "PS", false},
	"971": {"United Arab Emirates", "AE", false},
	"972": {"Israel", "IL", false},
	"973": {"Bahrain", "BH", false},
	"974": {"Qatar", "QA", false},
	"975": {"Bhutan", "BT", false},
	"976": {"Mongolia", "MN", false},
	"977": {"Nepal", "NP", false},
	"979": {"International / non-geographic", "001", false},
	"992": {"Tajikistan", "TJ", false},
	"993": {"Turkmenistan", "TM", false},
	"994": {"Azerbaijan", "AZ", false},
	"995": {"Georgia", "GE", false},
	"996": {"Kyrgyzstan", "KG", false},
	"998": {"Uzbekistan", "UZ", false},
}
