package tools

import (
	"context"
	"strings"
	"testing"
)

// TestDCF77DecodeHandler_HappyPath confirms the Spec handler
// decodes a DCF77 frame through to JSON. The test bit-string
// was generated with the internal/dcf77 buildFrame helper for:
// 14:35 Tuesday 2026-04-22 CEST.
func TestDCF77DecodeHandler_HappyPath(t *testing.T) {
	// Pre-computed bit-string for: min=35, hr=14, day=22, dow=2,
	// month=4, year=26, CEST=true. Generated by replicating the
	// internal/dcf77/buildFrame logic.
	bits := "000000000000000001001101011000010100010001010001000110010010"
	out, err := dcf77DecodeHandler(context.Background(), nil, map[string]any{
		"bits": bits,
	})
	if err != nil {
		t.Fatalf("handler: %v", err)
	}
	if !strings.Contains(out, `"formatted_time": "14:35"`) {
		t.Errorf("expected formatted_time 14:35 in output:\n%s", out)
	}
	if !strings.Contains(out, `"formatted_date": "2026-04-22"`) {
		t.Errorf("expected formatted_date 2026-04-22:\n%s", out)
	}
	if !strings.Contains(out, `"day_of_week_name": "Tuesday"`) {
		t.Errorf("expected Tuesday:\n%s", out)
	}
	if !strings.Contains(out, `"cest_active": true`) {
		t.Errorf("expected cest_active true:\n%s", out)
	}
	if !strings.Contains(out, `"all_parity_valid": true`) {
		t.Errorf("expected all_parity_valid true:\n%s", out)
	}
}

func TestDCF77DecodeHandler_RejectsEmpty(t *testing.T) {
	_, err := dcf77DecodeHandler(context.Background(), nil, map[string]any{"bits": ""})
	if err == nil {
		t.Fatal("want error for empty bits")
	}
}

func TestDCF77DecodeHandler_RejectsWrongLength(t *testing.T) {
	_, err := dcf77DecodeHandler(context.Background(), nil, map[string]any{
		"bits": strings.Repeat("0", 59),
	})
	if err == nil {
		t.Fatal("want error for 59-bit input")
	}
}
