// roca_detect.go — host-side ROCA (CVE-2017-15361) weak-RSA-key detector Spec,
// delegating to internal/roca.
//
// Wrap-vs-native: native — the in-tree fingerprint port (38 primes + 38 marker
// bitmasks from crocs-muni/roca detect.py) plus stdlib crypto/x509 and a native
// ssh-rsa wire parser. No GitHub API, no network, no new go.mod dependency.
// Flags RSA public keys generated by the vulnerable Infineon RSALib (TPMs,
// Yubikey 4/Neo, Gemalto, Estonian/Slovak eID) whose private key is
// practically factorable — offline, audit / IR triage.

package tools

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/xunholy/promptzero/internal/risk"
	"github.com/xunholy/promptzero/internal/roca"
)

func init() { //nolint:gochecknoinits
	Register(rocaDetectSpec)
}

var rocaDetectSpec = Spec{
	Name: "roca_detect",
	Description: "Detect **ROCA-vulnerable RSA keys** (CVE-2017-15361) — the Infineon RSALib flaw that " +
		"generated **factorable** primes. Keys produced by Infineon TPMs, **Yubikey 4/Neo**, Gemalto " +
		"IDPrime smartcards, and the **Estonian / Slovak national eID** cards have private keys that can be " +
		"recovered from the **public** key alone by the Coppersmith attack of Nemec et al. (CCS 2017). This " +
		"is core **certificate / SSH-key / smartcard audit**: given only a public key you can tell whether " +
		"its secret half is compromised, **offline**.\n\n" +
		"Accepts a bare RSA **modulus** (decimal or hex), a **PEM public key** (PKIX/SPKI or PKCS#1), a PEM " +
		"**X.509 certificate**, or an OpenSSH **ssh-rsa** authorized_key line; extracts the modulus and runs " +
		"the published **fingerprint** test (38 small-prime residue checks against the Infineon generator " +
		"structure). **No confidently-wrong output**: the fingerprint **never clears a vulnerable key** (a " +
		"negative is reliable), and a positive is reported as a near-certain hit confirmed only by the full " +
		"factorisation — surfaced in the note, not overclaimed. No network, no device, transmits nothing — " +
		"Low risk. Pairs with `secret_identify` and the PGP/keystore forensics tools.\n\n" +
		"Source: docs/catalog/gap-analysis.md (key-material forensics). Wrap-vs-native: native — the " +
		"fingerprint primes + markers are ported verbatim from crocs-muni/roca (detect.py), validated " +
		"against that project's ten fingerprint-positive test moduli; ssh-rsa is parsed natively off the " +
		"RFC 4253 wire format, so no x/crypto/ssh surface and no new go.mod dependency.",
	Schema: json.RawMessage(`{
		"type":"object",
		"properties":{
			"key":{"type":"string","description":"An RSA modulus (decimal or 0x-hex), a PEM public key (PKIX/SPKI or PKCS#1), a PEM X.509 certificate, or an OpenSSH ssh-rsa line."}
		},
		"required":["key"]
	}`),
	Required:  []string{"key"},
	Risk:      risk.Low,
	Group:     GroupHostTools,
	AgentOnly: false,
	Handler:   rocaDetectHandler,
}

func rocaDetectHandler(_ context.Context, _ *Deps, p map[string]any) (string, error) {
	key := strings.TrimSpace(str(p, "key"))
	if key == "" {
		return "", fmt.Errorf("roca_detect: 'key' is required")
	}
	res, err := roca.Detect(key)
	if err != nil {
		return "", fmt.Errorf("roca_detect: %w", err)
	}
	out, _ := json.MarshalIndent(res, "", "  ")
	return string(out), nil
}
