package macaroon

import (
	"encoding/hex"
	"testing"
)

// The binary_v1 and binary_v2 vectors below are the cross-implementation
// macaroons from pymacaroons' tests/functional_tests/serialization_tests.py
// (generated by github.com/go-macaroon/macaroon to test deserialization). Both
// encode the same macaroon, so decoding either must yield identical fields:
//
//	location   = "my location"
//	identifier = "my identifier"
//	caveat[0]  = first-party,  id "fp caveat"
//	caveat[1]  = third-party,  id "tp caveat", location "tp location", vid set
//	signature  = 483b3881c9990e5099cb6695da3164daa64da60417bcaf9e9dc4c0a9968f6636
const (
	binaryV1 = "MDAxOWxvY2F0aW9uIG15IGxvY2F0aW9uCjAwMWRpZGVudGlmaWVyIG15IGlkZW50aWZpZXIK" +
		"MDAxMmNpZCBmcCBjYXZlYXQKMDAxMmNpZCB0cCBjYXZlYXQKMDA1MXZpZCAAAAAAAAAAAAAAAAAA" +
		"AAAAAAAAAAAAAAACn8yDEet8ud+825gOjM0pZOVE8/HpV6Zqxac+kl0BYToVaY64VfiwHj5rWgBR" +
		"EOkKMDAxM2NsIHRwIGxvY2F0aW9uCjAwMmZzaWduYXR1cmUgSDs4gcmZDlCZy2aV2jFk2qZNpgQX" +
		"vK+encTAqZaPZjYK"
	binaryV2 = "AgELbXkgbG9jYXRpb24CDW15IGlkZW50aWZpZXIAAglmcCBjYXZlYXQAAQt0cCBsb2NhdGlvbg" +
		"IJdHAgY2F2ZWF0BEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACn8yDEet8ud+825gOjM0pZOVE8/" +
		"HpV6Zqxac+kl0BYToVaY64VfiwHj5rWgBREOkAAAYgSDs4gcmZDlCZy2aV2jFk2qZNpgQXvK+enc" +
		"TAqZaPZjY"

	wantSigHex = "483b3881c9990e5099cb6695da3164daa64da60417bcaf9e9dc4c0a9968f6636"
)

func assertGoldMacaroon(t *testing.T, m *Macaroon, wantVersion int) {
	t.Helper()
	if m.Version != wantVersion {
		t.Errorf("Version = %d, want %d", m.Version, wantVersion)
	}
	if m.Location != "my location" {
		t.Errorf("Location = %q, want %q", m.Location, "my location")
	}
	if string(m.Identifier) != "my identifier" {
		t.Errorf("Identifier = %q, want %q", m.Identifier, "my identifier")
	}
	if got := hex.EncodeToString(m.Signature); got != wantSigHex {
		t.Errorf("Signature = %s, want %s", got, wantSigHex)
	}
	if len(m.Caveats) != 2 {
		t.Fatalf("len(Caveats) = %d, want 2", len(m.Caveats))
	}
	if string(m.Caveats[0].ID) != "fp caveat" || !m.Caveats[0].FirstParty() {
		t.Errorf("caveat[0] = %+v, want first-party id %q", m.Caveats[0], "fp caveat")
	}
	c1 := m.Caveats[1]
	if string(c1.ID) != "tp caveat" || c1.Location != "tp location" || c1.FirstParty() {
		t.Errorf("caveat[1] = id=%q location=%q firstParty=%v, want third-party id %q location %q",
			c1.ID, c1.Location, c1.FirstParty(), "tp caveat", "tp location")
	}
}

func TestDecodeBase64_GoldVectorV1(t *testing.T) {
	m, err := DecodeBase64(binaryV1)
	if err != nil {
		t.Fatalf("DecodeBase64(v1): %v", err)
	}
	assertGoldMacaroon(t, m, 1)
}

func TestDecodeBase64_GoldVectorV2(t *testing.T) {
	m, err := DecodeBase64(binaryV2)
	if err != nil {
		t.Fatalf("DecodeBase64(v2): %v", err)
	}
	assertGoldMacaroon(t, m, 2)
}

// Both serializations must decode to the same logical macaroon, including the
// verification key ID bytes of the third-party caveat.
func TestV1AndV2Agree(t *testing.T) {
	m1, err := DecodeBase64(binaryV1)
	if err != nil {
		t.Fatalf("v1: %v", err)
	}
	m2, err := DecodeBase64(binaryV2)
	if err != nil {
		t.Fatalf("v2: %v", err)
	}
	if hex.EncodeToString(m1.Caveats[1].VID) != hex.EncodeToString(m2.Caveats[1].VID) {
		t.Errorf("VID mismatch between v1 (%x) and v2 (%x)", m1.Caveats[1].VID, m2.Caveats[1].VID)
	}
	if len(m1.Caveats[1].VID) == 0 {
		t.Error("expected non-empty VID on third-party caveat")
	}
}

func TestDecode_Errors(t *testing.T) {
	cases := map[string][]byte{
		"empty":           {},
		"unknown leading": {0x99, 0x01, 0x02},
		"v2 truncated":    {0x02, 0x01, 0x05, 'a', 'b'}, // length 5 but only 2 bytes follow
		"v1 bad hex":      []byte("zzzz garbage"),
		"v1 short length": []byte("0002"),                      // length below the 4-byte prefix
		"v2 no signature": {0x02, 0x02, 0x01, 'i', 0x00, 0x00}, // header + EOS + caveats-EOS, no sig
	}
	for name, raw := range cases {
		if _, err := Decode(raw); err == nil {
			t.Errorf("%s: expected error, got nil", name)
		}
	}
}

func FuzzDecode(f *testing.F) {
	for _, v := range []string{binaryV1, binaryV2} {
		if raw, err := DecodeBase64(v); err == nil {
			_ = raw
		}
	}
	f.Add([]byte{0x02, 0x01, 0x03, 'a', 'b', 'c'})
	f.Add([]byte("0019location x\n"))
	f.Fuzz(func(_ *testing.T, raw []byte) {
		// Must never panic regardless of input.
		_, _ = Decode(raw)
	})
}
