// SPDX-License-Identifier: AGPL-3.0-or-later

// Package debruijn generates binary de Bruijn sequences B(2,n) — the
// optimal bit stream for brute-forcing fixed-code (non-rolling) receivers.
//
// # Wrap-vs-native judgement
//
// Native. A de Bruijn sequence is a classic, public combinatorial object
// generated by a few lines of the standard Lyndon-word (FKM) algorithm — no
// dependency, no hardware. Its pentest relevance is Samy Kamkar's OpenSesame
// technique: a fixed-code receiver that accepts a continuous bit stream can
// be brute-forced by sliding an n-bit window across the de Bruijn sequence,
// so all 2^n codes are exercised in 2^n + n - 1 transmitted bits instead of
// the 2^n * n bits a naive per-code sweep sends — an ~n-fold speedup. The
// existing subghz_bruteforce_generate emits a naive sequential Princeton
// sweep; this is the optimal-sequence complement. Generation only — it
// produces a bit stream, transmits nothing (pair with an OOK/TX stage), so
// it is Low risk.
//
// # Verifiable
//
// Correctness is self-checking: the defining property is that every length-n
// binary string occurs exactly once as a window of the (cyclic) sequence —
// the unit tests assert that all 2^n windows of the linear form are present
// and unique, so there is no confidently-wrong risk.
//
// # Deliberately bounded
//
// The sequence length is 2^n, which grows exponentially; n is capped at 20
// (about a million bits) to keep a single tool response sane. Larger code
// widths must be streamed/windowed externally (the sequence for a 24-bit
// code is inherently 16 Mbit — that is the nature of the search, not a
// limitation of the generator).
package debruijn

import "fmt"

// MaxBits is the largest code width this generator will materialise in one
// call (2^MaxBits bits).
const MaxBits = 20

// Sequence returns the cyclic binary de Bruijn sequence B(2,n) as a slice
// of 0/1 bytes of length 2^n, in which every length-n binary string appears
// exactly once as a cyclic window. n must be in [1, MaxBits].
func Sequence(n int) ([]byte, error) {
	if n < 1 || n > MaxBits {
		return nil, fmt.Errorf("debruijn: n=%d out of range [1,%d]", n, MaxBits)
	}
	const k = 2
	a := make([]int, k*n+1)
	out := make([]byte, 0, 1<<uint(n))
	var db func(t, p int)
	db = func(t, p int) {
		if t > n {
			if n%p == 0 {
				for j := 1; j <= p; j++ {
					out = append(out, byte(a[j]))
				}
			}
			return
		}
		a[t] = a[t-p]
		db(t+1, p)
		for j := a[t-p] + 1; j < k; j++ {
			a[t] = j
			db(t+1, t)
		}
	}
	db(1, 1)
	return out, nil
}

// Linear returns the de Bruijn sequence with the first n-1 bits appended so
// that every length-n window appears non-cyclically — the form transmitted
// for a sliding-window brute force. Its length is 2^n + n - 1.
func Linear(n int) ([]byte, error) {
	seq, err := Sequence(n)
	if err != nil {
		return nil, err
	}
	out := make([]byte, 0, len(seq)+n-1)
	out = append(out, seq...)
	out = append(out, seq[:n-1]...)
	return out, nil
}
