package emv

// Curated EMV BER-TLV tag name lookup. Tags chosen from EMV Books
// 1-4 (the ones an operator most often sees in a saved NFC capture).
// Not exhaustive — proprietary tags in the 0xDF range vary by issuer
// and aren't useful to enumerate. When a tag isn't here, TagName
// returns "" and callers render the tag hex only.
//
// Keep this list ordered roughly by tag number so future additions
// stay easy to spot. Add a one-line "tag → name" entry; the parser
// does not depend on coverage being complete.
var tagNames = map[uint32]string{
	// File / template tags.
	0x4F: "Application Identifier (AID)",
	0x50: "Application Label",
	0x57: "Track 2 Equivalent Data",
	0x5A: "Application Primary Account Number (PAN)",
	0x61: "Application Template",
	0x6F: "File Control Information (FCI) Template",
	0x70: "READ RECORD Response Message Template",
	0x71: "Issuer Script Template 1",
	0x72: "Issuer Script Template 2",
	0x73: "Directory Discretionary Template",
	0x77: "Response Message Template Format 2",
	0x80: "Response Message Template Format 1",
	0x82: "Application Interchange Profile (AIP)",
	0x83: "Command Template",
	0x84: "Dedicated File (DF) Name",
	0x86: "Issuer Script Command",
	0x87: "Application Priority Indicator",
	0x88: "Short File Identifier (SFI)",
	0x89: "Authorisation Code",
	0x8A: "Authorisation Response Code",
	0x8C: "Card Risk Management Data Object List 1 (CDOL1)",
	0x8D: "Card Risk Management Data Object List 2 (CDOL2)",
	0x8E: "Cardholder Verification Method (CVM) List",
	0x8F: "Certification Authority Public Key Index",
	0x90: "Issuer Public Key Certificate",
	0x91: "Issuer Authentication Data",
	0x92: "Issuer Public Key Remainder",
	0x93: "Signed Static Application Data",
	0x94: "Application File Locator (AFL)",
	0x95: "Terminal Verification Results (TVR)",
	0x97: "Transaction Certificate Data Object List (TDOL)",
	0x98: "Transaction Certificate (TC) Hash Value",
	0x99: "Transaction PIN Data",
	0x9A: "Transaction Date",
	0x9B: "Transaction Status Information",
	0x9C: "Transaction Type",
	0x9D: "Directory Definition File (DDF) Name",
	0xA5: "FCI Proprietary Template",

	// Multi-byte 5Fxx tags (cardholder + currency metadata).
	0x5F20: "Cardholder Name",
	0x5F24: "Application Expiration Date",
	0x5F25: "Application Effective Date",
	0x5F28: "Issuer Country Code",
	0x5F2A: "Transaction Currency Code",
	0x5F2D: "Language Preference",
	0x5F30: "Service Code",
	0x5F34: "PAN Sequence Number",
	0x5F36: "Transaction Currency Exponent",
	0x5F50: "Issuer URL",
	0x5F53: "International Bank Account Number (IBAN)",
	0x5F54: "Bank Identifier Code (BIC)",
	0x5F55: "Issuer Country Code (alpha2)",
	0x5F56: "Issuer Country Code (alpha3)",

	// Multi-byte 9Fxx tags (transaction + terminal data).
	0x9F01: "Acquirer Identifier",
	0x9F02: "Amount Authorised",
	0x9F03: "Amount Other",
	0x9F04: "Amount Other (binary)",
	0x9F05: "Application Discretionary Data",
	0x9F06: "Application Identifier (Terminal)",
	0x9F07: "Application Usage Control",
	0x9F08: "Application Version Number (ICC)",
	0x9F09: "Application Version Number (Terminal)",
	0x9F0B: "Cardholder Name Extended",
	0x9F0D: "Issuer Action Code — Default",
	0x9F0E: "Issuer Action Code — Denial",
	0x9F0F: "Issuer Action Code — Online",
	0x9F10: "Issuer Application Data",
	0x9F11: "Issuer Code Table Index",
	0x9F12: "Application Preferred Name",
	0x9F13: "Last Online Application Transaction Counter (ATC) Register",
	0x9F14: "Lower Consecutive Offline Limit",
	0x9F15: "Merchant Category Code",
	0x9F16: "Merchant Identifier",
	0x9F17: "PIN Try Counter",
	0x9F18: "Issuer Script Identifier",
	0x9F1A: "Terminal Country Code",
	0x9F1B: "Terminal Floor Limit",
	0x9F1C: "Terminal Identification",
	0x9F1D: "Terminal Risk Management Data",
	0x9F1E: "Interface Device (IFD) Serial Number",
	0x9F1F: "Track 1 Discretionary Data",
	0x9F20: "Track 2 Discretionary Data",
	0x9F21: "Transaction Time",
	0x9F26: "Application Cryptogram (AC)",
	0x9F27: "Cryptogram Information Data (CID)",
	0x9F2D: "ICC PIN Encipherment Public Key Certificate",
	0x9F2E: "ICC PIN Encipherment Public Key Exponent",
	0x9F2F: "ICC PIN Encipherment Public Key Remainder",
	0x9F32: "Issuer Public Key Exponent",
	0x9F33: "Terminal Capabilities",
	0x9F34: "Cardholder Verification Method (CVM) Results",
	0x9F35: "Terminal Type",
	0x9F36: "Application Transaction Counter (ATC)",
	0x9F37: "Unpredictable Number",
	0x9F38: "Processing Options Data Object List (PDOL)",
	0x9F39: "Point-of-Service (POS) Entry Mode",
	0x9F40: "Additional Terminal Capabilities",
	0x9F41: "Transaction Sequence Counter",
	0x9F42: "Application Currency Code",
	0x9F44: "Application Currency Exponent",
	0x9F45: "Data Authentication Code",
	0x9F46: "ICC Public Key Certificate",
	0x9F47: "ICC Public Key Exponent",
	0x9F48: "ICC Public Key Remainder",
	0x9F49: "Dynamic Data Authentication Data Object List (DDOL)",
	0x9F4A: "Static Data Authentication Tag List",
	0x9F4B: "Signed Dynamic Application Data",
	0x9F4C: "ICC Dynamic Number",
	0x9F4D: "Log Entry",
	0x9F4E: "Merchant Name and Location",
	0x9F4F: "Log Format",
	0x9F66: "Terminal Transaction Qualifiers (TTQ)",
	0x9F6C: "Card Transaction Qualifiers (CTQ)",
	0x9F6E: "Form Factor Indicator / Third Party Data",
}

// TagName returns the canonical EMV name for a tag, or the empty
// string when the tag isn't in the curated table. Lookups are
// case-insensitive on the encoded form because the input is a
// uint32 (no character-case ambiguity).
func TagName(tag uint32) string {
	return tagNames[tag]
}
