package btuuid

// services maps SIG-assigned 16-bit GATT Service UUIDs to their
// canonical names. Source: Bluetooth Assigned Numbers — GATT
// Services document. Covers the documented services operators
// commonly enumerate via bluetoothctl / nRF Connect / btmon /
// Flipper BT scan.
//
// Operators can extend this table by editing the file; the
// lookup doesn't depend on coverage being exhaustive.
var services = map[string]string{
	// Standard GATT services (0x18xx range)
	"1800": "Generic Access",
	"1801": "Generic Attribute",
	"1802": "Immediate Alert",
	"1803": "Link Loss",
	"1804": "TX Power",
	"1805": "Current Time",
	"1806": "Reference Time Update",
	"1807": "Next DST Change",
	"1808": "Glucose",
	"1809": "Health Thermometer",
	"180A": "Device Information",
	"180D": "Heart Rate",
	"180E": "Phone Alert Status",
	"180F": "Battery",
	"1810": "Blood Pressure",
	"1811": "Alert Notification",
	"1812": "Human Interface Device",
	"1813": "Scan Parameters",
	"1814": "Running Speed and Cadence",
	"1815": "Automation IO",
	"1816": "Cycling Speed and Cadence",
	"1818": "Cycling Power",
	"1819": "Location and Navigation",
	"181A": "Environmental Sensing",
	"181B": "Body Composition",
	"181C": "User Data",
	"181D": "Weight Scale",
	"181E": "Bond Management",
	"181F": "Continuous Glucose Monitoring",
	"1820": "Internet Protocol Support",
	"1821": "Indoor Positioning",
	"1822": "Pulse Oximeter",
	"1823": "HTTP Proxy",
	"1824": "Transport Discovery",
	"1825": "Object Transfer",
	"1826": "Fitness Machine",
	"1827": "Mesh Provisioning",
	"1828": "Mesh Proxy",
	"1829": "Reconnection Configuration",
	"183A": "Insulin Delivery",
	"183B": "Binary Sensor",
	"183C": "Emergency Configuration",
	"183D": "Authorization Control",
	"183E": "Physical Activity Monitor",
	"183F": "Elapsed Time",
	"1840": "Generic Health Sensor",
	"1843": "Audio Input Control",
	"1844": "Volume Control",
	"1845": "Volume Offset Control",
	"1846": "Coordinated Set Identification",
	"1847": "Device Time",
	"1848": "Media Control",
	"1849": "Generic Media Control",
	"184A": "Constant Tone Extension",
	"184B": "Telephone Bearer",
	"184C": "Generic Telephone Bearer",
	"184D": "Microphone Control",
	"184E": "Audio Stream Control",
	"184F": "Broadcast Audio Scan",
	"1850": "Published Audio Capabilities",
	"1851": "Basic Audio Announcement",
	"1852": "Broadcast Audio Announcement",
	"1853": "Common Audio",
	"1854": "Hearing Aid",
	"1855": "TMAS",
	"1856": "Public Broadcast Announcement",
	"1857": "Electronic Shelf Label",
	"1858": "Gaming Audio",
	"1859": "Mesh Proxy Solicitation",

	// Well-known proprietary 16-bit service UUIDs (0xFEXX
	// range — assigned to SIG members)
	"FEAA": "Eddystone (Google)",
	"FE9F": "Google Fast Pair",
	"FD6F": "Exposure Notification (COVID-19)",
	"FDA5": "Apple AirTag (Find My)",
	"FED2": "Apple iBeacon",
	"FEED": "Tile, Inc.",
	"FCD2": "Allterco Robotics (Shelly)",
	"FE2C": "Google",
	"FE19": "Google LLC",
	"FE0F": "Philips Lighting B.V.",
	"FE7D": "Bose Corporation",
	"FE03": "Amazon.com Services, LLC",
	"FE0C": "United Technologies Automotive",
	"FE9E": "Apple LE Audio",
}
